ALTER TABLE "UserSettings"
ADD COLUMN IF NOT EXISTS "waterDayStart" VARCHAR(5) NOT NULL DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS "waterDayEnd" VARCHAR(5) NOT NULL DEFAULT '20:00',
ADD COLUMN IF NOT EXISTS "waterPaceIntervalHours" INTEGER NOT NULL DEFAULT 2;
