import {z} from 'zod';
import {recordDate} from './modules';
import {workDefaults} from './work-calculations';
const money=z.number().min(0).max(10000000),percent=z.number().min(0).max(300),text=z.string().trim().max(2000).default(''),id=z.string().min(1).max(100).nullable().default(null),time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable().default(null);
export const workContractInput=z.object({
  baseSalary:money,standardMinutes:z.number().int().min(1).max(1440),defaultBreakMinutes:z.number().int().min(0).max(480),monthlyHours:z.number().positive().max(744),contributionBasePercent:percent.max(100),mealPerDay:money,travelAllowance:money,vacationDays:z.number().min(0).max(366),vacationCarryover:z.number().min(0).max(1000),sickEntitlement:z.number().min(0).max(1000),sickPayPercent:percent,employeePensionPercent:percent,employerPensionPercent:percent,severancePercent:percent,employeeTrainingPercent:percent,employerTrainingPercent:percent,overtimeFirstMinutes:z.number().int().min(0).max(1440),overtimeFirstPercent:percent,overtimeNextPercent:percent,workDays:z.array(z.number().int().min(0).max(6)).min(1).max(7)
}).strict();
export function parseContract(value:unknown){return workContractInput.parse({...workDefaults,...(value&&typeof value==='object'?value:{})});}
export const workEntryInput=z.object({date:recordDate,type:z.enum(['WORK','HOME','TRAVEL','OTHER','VACATION','SICK']),startTime:time,endTime:time,endDate:recordDate.nullable().default(null),breakMinutes:z.number().int().min(0).max(1440).default(0),overtimeApproved:z.boolean().default(false),distanceKm:z.number().min(0).max(100000).default(0),tripId:id,notes:text}).strict().refine(v=>Boolean(v.startTime)===Boolean(v.endTime),'יש להזין גם כניסה וגם יציאה, או להשאיר את שתיהן ריקות.').refine(v=>!['WORK','HOME'].includes(v.type)||Boolean(v.startTime),'לעבודה יש להזין שעות כניסה ויציאה.').refine(v=>!['SICK','VACATION'].includes(v.type)||!v.startTime,'מחלה וחופשה נרשמות כיום היעדרות ללא שעות עבודה.');
export const timeOffInput=z.object({type:z.enum(['SICK','VACATION']),startDate:recordDate,endDate:recordDate,notes:text}).strict().refine(v=>v.endDate>=v.startDate,'תאריך הסיום חייב להיות לאחר ההתחלה.').refine(v=>(Date.parse(v.endDate)-Date.parse(v.startDate))/86400000<=365,'ניתן לרשום עד שנה בכל פעם.');
export const workTripInput=z.object({destination:z.string().trim().min(1).max(200),startDate:recordDate,endDate:recordDate,status:z.enum(['DRAFT','APPROVED','COMPLETED']),project:text,client:text,purpose:text,orderNumber:text,flightDetails:text,hotelDetails:text,participants:text,perDiem:money,perDiemCurrency:z.enum(['ILS','USD','EUR','GBP','CHF','CAD','AUD','JPY'])}).strict().refine(v=>v.endDate>=v.startDate,'תאריך הסיום חייב להיות לאחר ההתחלה.');
export const expenseInput=z.object({tripId:id,date:recordDate,category:z.enum(['HOTEL','FLIGHT','TAXI','MEALS','PARKING','OTHER']),amount:z.number().positive().max(10000000),currency:z.enum(['ILS','USD','EUR','GBP','CHF','CAD','AUD','JPY']),exchangeRate:z.number().positive().max(1000000).nullable().default(null),paymentSource:z.enum(['PERSONAL','COMPANY']),reimbursable:z.boolean(),paid:z.boolean().default(false),notes:text,documentId:id}).strict().refine(v=>v.paymentSource!=='COMPANY'||!v.reimbursable,'הוצאה בכרטיס חברה אינה החזר אישי.');
