ALTER TABLE "UserSettings" ADD COLUMN IF NOT EXISTS "vehicleReminderEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "roadMonth" INTEGER;
ALTER TABLE "VehiclePolicy" ADD COLUMN IF NOT EXISTS "reminderDays" INTEGER;
ALTER TABLE "VehiclePolicy" ADD COLUMN IF NOT EXISTS "reminderTime" VARCHAR(5) NOT NULL DEFAULT '09:00';
ALTER TABLE "VehicleReminder" ADD COLUMN IF NOT EXISTS "expiryDate" DATE;
ALTER TABLE "VehicleReminder" ADD COLUMN IF NOT EXISTS "licenseFee" DECIMAL(12,2);
ALTER TABLE "VehicleReminder" ADD COLUMN IF NOT EXISTS "testFee" DECIMAL(12,2);
ALTER TABLE "VehicleReminder" ADD COLUMN IF NOT EXISTS "reminderDays" INTEGER;
ALTER TABLE "VehicleReminder" ADD COLUMN IF NOT EXISTS "reminderTime" VARCHAR(5) NOT NULL DEFAULT '09:00';
