import { test, expect } from '@playwright/test';
import { Client } from 'pg';
import { createHash } from 'node:crypto';
const runId = Date.now();
const emails = [`sbo-test-a-${runId}@example.test`, `sbo-test-b-${runId}@example.test`];
const password = 'Only for automated tests 123!';
const origin = { Origin: 'http://localhost:3000' };
test.afterAll(async () => {
  const client = new Client({ connectionString: process.env.DATABASE_URL });
  await client.connect();
  await client.query('DELETE FROM "User" WHERE email = ANY($1::text[])', [emails]);
  await client.query('DELETE FROM "LoginAttempt" WHERE key = ANY($1::text[])', [emails.map(email => createHash('sha256').update(email).digest('hex'))]);
  await client.end();
});
test('registration, CRUD, isolation, responsive navigation and logout', async ({ page, browser, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  expect((await request.get('/api/tasks')).status()).toBe(401);
  await page.goto('/');
  await expect(page).toHaveURL(/login/);
  await page.getByRole('link', { name: 'יצירת חשבון', exact: true }).click();
  await page.getByLabel('שם', { exact: true }).fill('Alex');
  await page.getByLabel('כתובת אימייל').fill(emails[0]);
  await page.getByLabel('סיסמה').fill(password);
  await page.getByRole('button', { name: 'יצירת חשבון', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'שלום, Alex' })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.getByRole('link', { name: 'זמן ומשימות', exact: true }).first().click();
  await page.getByRole('button', { name: 'יצירת משימה', exact: true }).click();
  await page.getByLabel('שם משימה').fill('Plan the week');
  await page.getByLabel('תיאור משימה', { exact: false }).fill('Choose three priorities for the week.');
  const taskDialog=page.locator('dialog[open]');
  await taskDialog.locator('select').nth(1).selectOption('HIGH');
  await taskDialog.locator('input[type="date"]').first().fill('2026-09-15');
  await page.getByRole('button', { name: 'שמירה', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan the week', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Plan the week', exact: true })).toBeVisible();
  const tasks = await (await page.request.get('/api/tasks')).json();
  const id = tasks[0].id;
  expect(tasks[0].startDate).toBe('2026-09-15');
  const other = await browser.newContext();
  expect((await other.request.post('http://localhost:3000/api/auth/register', { headers: origin, data: { name: 'Other account', email: emails[1], password } })).status()).toBe(200);
  expect(await (await other.request.get('http://localhost:3000/api/tasks')).json()).toEqual([]);
  const taskData = { title:'Attempt to change another account',description:'',status:'TODO',priority:'LOW',startDate:null,endDate:null,startTime:null,endTime:null,color:null,category:null,recurrence:'NONE',recurrenceDays:[],recurrenceUntil:null,showOnCalendar:true,reminderMinutes:null };
  expect((await other.request.patch(`http://localhost:3000/api/tasks/${id}`, { headers: origin, data: taskData })).status()).toBe(404);
  expect((await other.request.delete(`http://localhost:3000/api/tasks/${id}`, { headers: origin })).status()).toBe(404);
  expect((await page.request.post('/api/tasks', { headers: { Origin: 'https://untrusted.example' }, data: taskData })).status()).toBe(403);
  expect((await page.request.post('/api/tasks', { headers: origin, data: { ...taskData, startDate: '2026-02-30' } })).status()).toBe(400);
  await other.close();
  await page.getByRole('button', { name: 'עריכת Plan the week', exact: true }).click();
  await page.getByLabel('שם משימה').fill('Plan a focused week');
  await page.locator('dialog[open] select').first().selectOption('IN_PROGRESS');
  await page.getByRole('button', { name: 'שמירה', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan a focused week' })).toBeVisible();
  await expect(page.getByRole('article').getByText('בתהליך', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'סיום Plan a focused week', exact: true }).click();
  await expect(page.getByRole('button', { name: 'פתיחת Plan a focused week' })).toBeVisible();
  await page.getByRole('button', { name: 'משימות שהסתיימו', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan a focused week' })).toBeVisible();
  await page.getByRole('button', { name: 'פתיחת Plan a focused week' }).click();
  await expect(page.getByRole('heading', { name: 'Plan a focused week' })).not.toBeVisible();
  await page.getByRole('button', { name: 'כלל המשימות', exact: true }).click();
  await page.getByLabel('חיפוש משימות').fill('no matching task');
  await expect(page.getByText('אין משימות ברשימה הזאת.')).toBeVisible();
  await page.getByLabel('חיפוש משימות').fill('');
  await page.screenshot({ path: 'test-results/tasks-desktop.png', fullPage: true });
  for (const width of [390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    await page.goto('/');
    await expect(page.getByRole('heading', { name: 'שלום, Alex' })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `test-results/dashboard-${width}.png`, fullPage: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('navigation', { name: 'ניווט בנייד' }).getByRole('link', { name: 'מים', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'צריכת מים יומית' })).toBeVisible();
  await page.getByRole('navigation', { name: 'ניווט בנייד' }).getByRole('link', { name: 'משימות', exact: true }).click();
  await page.getByRole('button', { name: 'מחיקת Plan a focused week', exact: true }).click();
  await page.getByRole('button', { name: 'מחיקה', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Plan a focused week' })).not.toBeVisible();
  const db = new Client({ connectionString: process.env.DATABASE_URL });
  await db.connect();
  expect(Number((await db.query('SELECT count(*) FROM "TaskEvent" WHERE "taskId" = $1', [id])).rows[0].count)).toBe(5);
  await db.end();
  await page.getByRole('button', { name: 'התנתקות', exact: true }).filter({ visible: true }).click();
  await expect(page).toHaveURL(/login/);
  expect((await page.request.get('/api/tasks')).status()).toBe(401);
  await page.getByLabel('כתובת אימייל').fill(emails[0]);
  await page.getByLabel('סיסמה').fill(password);
  await page.getByRole('button', { name: 'התחברות', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'שלום, Alex' })).toBeVisible();
  expect(errors).toEqual([]);
});
