import {test,expect} from '@playwright/test';
import {Client} from 'pg';
import {mkdirSync,writeFileSync} from 'node:fs';
const headers={Origin:'http://localhost:3000'},stamp=Date.now(),emails=[`work-a-${stamp}@example.test`,`work-b-${stamp}@example.test`];
test.afterAll(async()=>{const client=new Client({connectionString:process.env.DATABASE_URL});await client.connect();await client.query('DELETE FROM "User" WHERE email=ANY($1::text[])',[emails]);await client.end();});
test('work tracking, contract, leave, trip expenses, files, exports and mobile layouts',async({page,browser,request})=>{
  test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  expect((await request.get('/api/work/data')).status()).toBe(401);
  expect((await page.request.post('/api/auth/register',{headers,data:{name:'בדיקת עבודה',email:emails[0],password:'OnlyTesting123!'}})).ok()).toBeTruthy();
  const entry={date:'2026-10-01',type:'WORK',startTime:'08:00',endTime:'19:00',endDate:'2026-10-01',breakMinutes:30,overtimeApproved:false,distanceKm:0,tripId:null,notes:'יום עבודה'};
  let response=await page.request.post('/api/work/entries',{headers,data:entry});expect(response.ok()).toBeTruthy();const entryId=(await response.json()).id;
  expect((await page.request.post('/api/work/entries',{headers,data:entry})).status()).toBe(409);
  expect((await page.request.patch(`/api/work/entries/${entryId}`,{headers,data:{...entry,overtimeApproved:true}})).ok()).toBeTruthy();
  expect((await page.request.post('/api/work/time-off',{headers,data:{type:'SICK',startDate:'2026-10-04',endDate:'2026-10-04',notes:'אישור מחלה'}})).ok()).toBeTruthy();
  expect((await page.request.post('/api/work/time-off',{headers,data:{type:'VACATION',startDate:'2026-10-06',endDate:'2026-10-07',notes:''}})).ok()).toBeTruthy();
  const trip={destination:'פריז, צרפת',startDate:'2026-10-10',endDate:'2026-10-12',status:'APPROVED',project:'SBO',client:'לקוח',purpose:'פגישה',orderNumber:'1001',flightDetails:'LY flight',hotelDetails:'מלון',participants:'אני',perDiem:50,perDiemCurrency:'EUR'};
  response=await page.request.post('/api/work/trips',{headers,data:trip});expect(response.ok()).toBeTruthy();const tripId=(await response.json()).id;
  const document=await page.request.post('/api/work/documents',{headers,multipart:{file:{name:'receipt.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWb8AAAAASUVORK5CYII=','base64')},category:'RECEIPT',tripId}});expect(document.ok()).toBeTruthy();const documentId=(await document.json()).id;
  const expense={tripId,date:'2026-10-10',category:'HOTEL',amount:100,currency:'EUR',exchangeRate:4,paymentSource:'PERSONAL',reimbursable:true,paid:false,notes:'מלון בפריז',documentId};
  response=await page.request.post('/api/work/expenses',{headers,data:expense});expect(response.ok()).toBeTruthy();const expenseId=(await response.json()).id;
  const historical=await page.request.get('/api/work/rate?currency=EUR&date=2025-10-01');expect(historical.ok()).toBeTruthy();const rate=await historical.json();expect(rate.exchangeRate).toBeGreaterThan(0);expect(rate.rateDate).toBe('2025-10-01');
  response=await page.request.post('/api/work/expenses',{headers,data:{...expense,tripId:null,date:'2025-10-01',exchangeRate:null,documentId:null}});expect(response.ok()).toBeTruthy();
  const automaticallyLinked=await page.request.post('/api/work/entries',{headers,data:{...entry,date:'2026-10-11',type:'TRAVEL',startTime:null,endTime:null,endDate:null,tripId:null,distanceKm:25,notes:'נסיעה'}});expect(automaticallyLinked.ok()).toBeTruthy();
  expect((await page.request.get(`/api/work/documents/${documentId}`)).headers()['cache-control']).toBe('private, no-store');
  const other=await browser.newContext({baseURL:'http://localhost:3000'});expect((await other.request.post('/api/auth/register',{headers,data:{name:'חשבון אחר',email:emails[1],password:'OnlyTesting123!'}})).ok()).toBeTruthy();
  for(const path of [`documents/${documentId}`,`entries/${entryId}`,`expenses/${expenseId}`,`trips/${tripId}`]){expect((await other.request.delete(`/api/work/${path}`,{headers})).status()).toBe(404);}
  expect((await other.request.get(`/api/work/documents/${documentId}`)).status()).toBe(404);expect((await other.request.post('/api/work/expenses',{headers,data:expense})).status()).toBe(404);await other.close();
  await page.setViewportSize({width:1440,height:900});await page.goto('/work');await expect(page.getByRole('heading',{name:'מרכז העבודה שלי'})).toBeVisible();
  await page.getByRole('button',{name:'תנאי חוזה'}).click();const modal=page.locator('.work-modal[open]');await modal.getByLabel('סיבוס ליום עבודה (₪)',{exact:true}).fill('40');await modal.getByRole('button',{name:'שמירה',exact:true}).click();await expect(modal).toHaveCount(0);
  expect((await (await page.request.get('/api/work/data')).json()).contract.mealPerDay).toBe(40);
  expect((await (await page.request.get('/api/work/data')).json()).entries.find((row:{notes:string})=>row.notes==='נסיעה').tripId).toBe(tripId);
  await page.getByRole('button',{name:'התחל עבודה',exact:true}).click();await expect(page.getByRole('heading',{name:'כרגע בעבודה'})).toBeVisible();
  await page.getByRole('button',{name:'הפסקה',exact:true}).click();await expect(page.getByRole('heading',{name:'כרגע בהפסקה'})).toBeVisible();await page.getByRole('button',{name:'חזרה מהפסקה'}).click();await page.getByRole('button',{name:'סיום עבודה'}).click();await expect(page.getByRole('heading',{name:'מוכנים ליום העבודה'})).toBeVisible();
  for(const title of ['לוח חודשי','סיכום חודש','שכר','חופשות ומחלה','נסיעה לחו״ל','הוצאות נסיעה','דוח שעות','מסמכים']){await page.locator('.work-tabs').getByRole('button',{name:title,exact:true}).click();await page.screenshot({path:`test-results/work-${title}.png`});}
  await page.locator('.work-tabs').getByRole('button',{name:'הוצאות נסיעה',exact:true}).click();await page.getByRole('button',{name:'עריכת הוצאה'}).click();await page.locator('.work-modal[open]').getByLabel('סכום',{exact:true}).fill('120');await page.locator('.work-modal[open]').getByRole('button',{name:'שמירה',exact:true}).click();await expect(page.locator('.work-modal[open]')).toHaveCount(0);expect((await (await page.request.get('/api/work/data')).json()).expenses[0].amount).toBe(120);
  for(const size of [{width:320,height:568},{width:390,height:844},{width:507,height:800},{width:834,height:1112},{width:1440,height:900}]){
    await page.setViewportSize(size);
    for(const name of ['לוח חודשי','סיכום חודש','שכר','חופשות ומחלה','נסיעה לחו״ל','הוצאות נסיעה','דוח שעות','מסמכים','היום שלי']){await page.locator('.work-tabs').getByRole('button',{name,exact:true}).click();expect(await page.locator('.workspace').evaluate(el=>el.scrollWidth<=el.clientWidth+1),`${name} at ${size.width}`).toBeTruthy();}
    expect(await page.locator('.workspace').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();
    if(size.width<1194){const nav=page.locator('.bottom-nav');let box=(await nav.boundingBox())!;expect(Math.abs(box.y+box.height-size.height)).toBeLessThan(2);await page.locator('.workspace').evaluate(el=>el.scrollTop=el.scrollHeight);box=(await nav.boundingBox())!;expect(Math.abs(box.y+box.height-size.height)).toBeLessThan(2);}
    await page.getByRole('button',{name:'הוספת יום'}).click();const dialog=page.locator('.work-modal[open]');expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBeTruthy();const controls=await dialog.locator('.work-form-grid>div:nth-child(-n+2) label> :last-child').evaluateAll(elements=>elements.map(el=>{const r=el.getBoundingClientRect();return {top:r.top,width:r.width,height:r.height};}));expect(Math.abs(controls[0].top-controls[1].top)).toBeLessThan(1);expect(Math.abs(controls[0].height-controls[1].height)).toBeLessThan(1);await page.screenshot({path:`test-results/work-modal-${size.width}.png`});await page.keyboard.press('Escape');
  }
  const exported=await page.request.get('/api/work/export?month=2026-10');expect(exported.ok()).toBeTruthy();mkdirSync('test-results',{recursive:true});writeFileSync('test-results/work-hours.xlsx',await exported.body());
  await page.goto('/work/report?month=2026-10');await expect(page.locator('.work-print-report')).toContainText('דוח שעות');await page.emulateMedia({media:'print'});await page.screenshot({path:'test-results/work-report-print.png',fullPage:true});await page.emulateMedia({media:'screen'});
  expect(errors).toEqual([]);
});
test('native picker clicks, creatine bounds, fixed navigation and onboard comparison',async({page})=>{
  test.setTimeout(120000);expect((await page.request.post('/api/auth/login',{headers,data:{email:emails[0],password:'OnlyTesting123!'}})).ok()).toBeTruthy();
  await page.setViewportSize({width:1440,height:900});await page.goto('/tasks');await page.getByRole('button',{name:/יצירת משימה/}).click();await page.evaluate(()=>{(window as unknown as {pickerCalls:number}).pickerCalls=0;HTMLInputElement.prototype.showPicker=function(){(window as unknown as {pickerCalls:number}).pickerCalls++;};});
  const dialog=page.locator('.task-editor-modal[open]');await dialog.locator('input[type=date]').first().click();await dialog.locator('input[type=time]').first().click();expect(await page.evaluate(()=>(window as unknown as {pickerCalls:number}).pickerCalls)).toBe(2);await page.keyboard.press('Escape');
  const vehicle=await page.request.post('/api/modules/vehicles',{headers,data:{name:'MAZDA 3',year:2024,roadMonth:5,licensePlate:'123-45-678',odometerKm:100000,fuelTankLiters:60}});expect(vehicle.ok()).toBeTruthy();const client=new Client({connectionString:process.env.DATABASE_URL});await client.connect();const vehicleId=(await client.query('SELECT v.id FROM "Vehicle" v JOIN "User" u ON u.id=v."userId" WHERE u.email=$1',[emails[0]])).rows[0].id;await client.end();
  const base={vehicleId,date:'2026-10-01',currentOdometerKm:100000,liters:40,pricePerLiter:7,isFullTank:true,dashboardKmPerLiter:10,notes:''};
  for(const payload of [base,{...base,date:'2026-10-02',currentOdometerKm:100100,liters:10,isFullTank:false},{...base,date:'2026-10-03',currentOdometerKm:100293,liters:21.5}]){const response=await page.request.post('/api/modules/fuel',{headers,data:payload});expect(response.ok(),await response.text()).toBeTruthy();}
  await page.goto('/vehicle');await expect(page).toHaveURL(/\/car$/);await expect(page.locator('.fuel-comparison')).toContainText('9.30');await expect(page.locator('.fuel-comparison')).toContainText('10.00');await expect(page.locator('.fuel-comparison')).toContainText('-7.0%');
  for(const size of [{width:320,height:568},{width:390,height:844},{width:507,height:800}]){await page.setViewportSize(size);await page.goto('/nutrition');const input=page.locator('.creatine-card input[type=time]');const bounds=await input.evaluate(el=>{const r=el.getBoundingClientRect(),card=el.closest('.creatine-card')!.getBoundingClientRect();return {left:r.left,right:r.right,cardLeft:card.left,cardRight:card.right,box:getComputedStyle(el).boxSizing};});expect(bounds.left).toBeGreaterThanOrEqual(bounds.cardLeft);expect(bounds.right).toBeLessThanOrEqual(bounds.cardRight);expect(bounds.box).toBe('border-box');await page.locator('.workspace').evaluate(el=>el.scrollTop=el.scrollHeight);const nav=(await page.locator('.bottom-nav').boundingBox())!;expect(Math.abs(nav.y+nav.height-size.height)).toBeLessThan(2);await page.screenshot({path:`test-results/creatine-${size.width}.png`});}
});
