"use client";
import type React from "react";

function hexToHsl(hex:string){const value=hex.replace('#',''),r=parseInt(value.slice(0,2),16)/255,g=parseInt(value.slice(2,4),16)/255,b=parseInt(value.slice(4,6),16)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),lightness=(max+min)/2;let hue=0,saturation=0;if(max!==min){const delta=max-min;saturation=lightness>.5?delta/(2-max-min):delta/(max+min);if(max===r)hue=((g-b)/delta+(g<b?6:0))*60;else if(max===g)hue=((b-r)/delta+2)*60;else hue=((r-g)/delta+4)*60;}return {h:Math.round(hue),s:Math.round(saturation*100),l:Math.round(lightness*100)};}
function hslToHex(h:number,s:number,l:number){s/=100;l/=100;const chroma=(1-Math.abs(2*l-1))*s,x=chroma*(1-Math.abs((h/60)%2-1)),m=l-chroma/2;let r=0,g=0,b=0;if(h<60){r=chroma;g=x}else if(h<120){r=x;g=chroma}else if(h<180){g=chroma;b=x}else if(h<240){g=x;b=chroma}else if(h<300){r=x;b=chroma}else{r=chroma;b=x}return '#'+[r,g,b].map(channel=>Math.round((channel+m)*255).toString(16).padStart(2,'0')).join('');}

export function ColorWheelPicker({value,onChange}:{value:string;onChange:(value:string)=>void}){
  const color=hexToHsl(value);
  function choose(event:React.PointerEvent<HTMLDivElement>){const rect=event.currentTarget.getBoundingClientRect(),radius=rect.width/2,dx=event.clientX-(rect.left+radius),dy=event.clientY-(rect.top+radius),distance=Math.min(radius,Math.hypot(dx,dy)),h=(Math.atan2(dy,dx)*180/Math.PI+90+360)%360,s=Math.round(distance/radius*100);onChange(hslToHex(h,s,color.l));}
  const markerRadius=color.s/100*50,markerAngle=(color.h-90)*Math.PI/180;
  return <div className="color-wheel-picker"><div className="color-wheel" role="slider" tabIndex={0} aria-label="בחירת גוון צבע" aria-valuemin={0} aria-valuemax={359} aria-valuenow={color.h} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);choose(event)}} onPointerMove={event=>{if(event.buttons)choose(event)}} onKeyDown={event=>{if(event.key==='ArrowLeft'||event.key==='ArrowDown')onChange(hslToHex((color.h+359)%360,color.s,color.l));if(event.key==='ArrowRight'||event.key==='ArrowUp')onChange(hslToHex((color.h+1)%360,color.s,color.l));}}><i style={{left:`calc(50% + ${Math.cos(markerAngle)*markerRadius}%)`,top:`calc(50% + ${Math.sin(markerAngle)*markerRadius}%)`,background:value}}/></div><div className="color-wheel-controls"><div className="selected-color"><span style={{background:value}}/><strong>{value.toUpperCase()}</strong></div><label>בהירות<input className="lightness-slider" aria-label="בהירות הצבע" type="range" min="15" max="85" value={color.l} style={{'--hue-color':`hsl(${color.h} 100% 50%)`} as React.CSSProperties} onChange={event=>onChange(hslToHex(color.h,color.s,Number(event.target.value)))}/></label><div className="shade-row">{[25,40,55,70].map(lightness=><button type="button" aria-label={`בהירות ${lightness}`} aria-pressed={Math.abs(color.l-lightness)<7} style={{background:hslToHex(color.h,Math.max(color.s,55),lightness)}} onClick={()=>onChange(hslToHex(color.h,Math.max(color.s,55),lightness))} key={lightness}/>)}</div></div></div>;
}
