"use client";
import { useState } from "react";
import { Search, Plus, RotateCcw } from "lucide-react";
import type { ModuleRecord } from "@/lib/modules";
type Food={id:string;name:string;brand?:string;calories:number;proteinG:number;carbsG:number;fatG:number;source?:string;sourceUrl?:string};
const one=(value:number)=>Number(Number(value).toFixed(1)).toLocaleString("he-IL",{maximumFractionDigits:1});
export function FoodBank({today,recentFoods,onFood,onQuickFood}:{today:string;recentFoods:ModuleRecord[];onFood:(food:Record<string,string|number|null>)=>void;onQuickFood:(food:Record<string,string|number|null>)=>Promise<void>}){
  const [query,setQuery]=useState(""),[foods,setFoods]=useState<Food[]>([]),[grams,setGrams]=useState(100),[busy,setBusy]=useState(false),[quickBusy,setQuickBusy]=useState<string|null>(null),[message,setMessage]=useState("");
  const saved=[...new Map(recentFoods.map(food=>[String(food.name).toLocaleLowerCase("he-IL"),food])).values()].slice(0,6);
  async function search(event:React.FormEvent){event.preventDefault();if(query.trim().length<2)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/nutrition/search?q=${encodeURIComponent(query.trim())}`);let body=await response.json();setFoods(body.foods??[]);if(body.hasOnline){const online=await fetch(`/api/nutrition/search?q=${encodeURIComponent(query.trim())}&online=1`);body=await online.json();setFoods(body.foods??[]);}if(body.error||!body.foods?.length)setMessage(body.error??"לא נמצאו תוצאות.");}catch{setMessage("לא ניתן לחפש כרגע.");}finally{setBusy(false);}}
  function choose(food:Food){const factor=grams/100;onFood({name:food.name,meal:"Other",date:today,quantity:grams,unit:"גרם",barcode:food.id.startsWith("common-")?"":food.id,calories:Math.round(food.calories*factor),proteinG:Number((food.proteinG*factor).toFixed(1)),carbsG:Number((food.carbsG*factor).toFixed(1)),fatG:Number((food.fatG*factor).toFixed(1))});}
  async function repeat(food:ModuleRecord){setQuickBusy(String(food.id));setMessage("");try{await onQuickFood({name:String(food.name),meal:"Other",date:today,quantity:Number(food.quantity)||100,unit:"גרם",barcode:String(food.barcode??""),calories:Math.round(Number(food.calories)||0),proteinG:Number(Number(food.proteinG||0).toFixed(1)),carbsG:Number(Number(food.carbsG||0).toFixed(1)),fatG:Number(Number(food.fatG||0).toFixed(1))});setMessage(`${String(food.name)} נוסף להיום.`);}catch{setMessage("לא ניתן להוסיף את הארוחה כרגע.");}finally{setQuickBusy(null);}}
  return <section className="food-bank"><div className="section-heading"><div><h2>מאגר מזון</h2><p>חיפוש בכמה מאגרים או הוספה מהירה מארוחות שכבר שמרת.</p></div></div>{saved.length>0&&<div className="saved-foods"><strong>הוספה מהירה</strong><div>{saved.map(food=><button type="button" disabled={quickBusy!==null} key={food.id} onClick={()=>void repeat(food)}><RotateCcw size={15}/><span>{String(food.name)}</span><small>{quickBusy===food.id?"מוסיף…":`${one(Number(food.calories))} קלוריות`}</small></button>)}</div></div>}<form onSubmit={search}><label className="food-search"><Search/><input aria-label="חיפוש במאגר המזון" value={query} onChange={event=>setQuery(event.target.value)} maxLength={100} placeholder="לדוגמה: חזה עוף, שווארמה"/></label><label className="food-grams"><span>כמות בגרם</span><input type="number" min="1" max="10000" inputMode="numeric" value={grams} onChange={event=>setGrams(Math.max(1,Number(event.target.value)||1))}/></label><button className="button primary" disabled={busy||query.trim().length<2}>{busy?"מחפש…":"חיפוש"}</button></form>{message&&<p className="module-hint">{message}</p>}<div className="food-results">{foods.map(food=><article key={food.id}><div><strong>{food.name}</strong>{food.brand&&<small>{food.brand}</small>}{food.source&&<small>{food.sourceUrl?<a href={food.sourceUrl} target="_blank" rel="noreferrer">{food.source}</a>:food.source}</small>}<span>{one(food.calories)} קלוריות · {one(food.proteinG)} חלבון · {one(food.carbsG)} פחמימות · {one(food.fatG)} שומן</span></div><button type="button" className="button secondary" onClick={()=>choose(food)}>הוספה <Plus size={16}/></button></article>)}</div></section>;
}
