"use client";
import { useState } from "react";
import { Search, Plus } from "lucide-react";

type Food={id:string;name:string;brand?:string;calories:number;proteinG:number;carbsG:number;fatG:number;source?:string;sourceUrl?:string};
export function FoodBank({today,onFood}:{today:string;onFood:(food:Record<string,string|number|null>)=>void}){
  const [query,setQuery]=useState(""),[foods,setFoods]=useState<Food[]>([]),[grams,setGrams]=useState(100),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function search(event:React.FormEvent){event.preventDefault();if(query.trim().length<2)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/nutrition/search?q=${encodeURIComponent(query.trim())}`);let body=await response.json();setFoods(body.foods??[]);if(body.hasOnline){const online=await fetch(`/api/nutrition/search?q=${encodeURIComponent(query.trim())}&online=1`);body=await online.json();setFoods(body.foods??[]);}if(body.error||!body.foods?.length)setMessage(body.error??"לא נמצאו תוצאות.");}catch{setMessage("לא ניתן לחפש כרגע.");}finally{setBusy(false);}}
  function choose(food:Food){const factor=grams/100;onFood({name:food.name,meal:"Other",date:today,quantity:grams,unit:"גרם",barcode:food.id.startsWith("common-")?"":food.id,calories:Math.round(food.calories*factor),proteinG:Number((food.proteinG*factor).toFixed(1)),carbsG:Number((food.carbsG*factor).toFixed(1)),fatG:Number((food.fatG*factor).toFixed(1))});}
  return <section className="food-bank"><div className="section-heading"><div><h2>מאגר מזון</h2><p>הערכים מוצגים ל־100 גרם ומתעדכנים לפי הכמות שבחרת.</p></div></div><form onSubmit={search}><label className="food-search"><Search/><input aria-label="חיפוש במאגר המזון" value={query} onChange={event=>setQuery(event.target.value)} maxLength={100} placeholder="לדוגמה: חזה עוף, שווארמה"/></label><label className="food-grams"><span>כמות בגרם</span><input type="number" min="1" max="10000" inputMode="numeric" value={grams} onChange={event=>setGrams(Math.max(1,Number(event.target.value)||1))}/></label><button className="button primary" disabled={busy||query.trim().length<2}>{busy?"מחפש…":"חיפוש"}</button></form>{message&&<p className="module-hint">{message}</p>}<div className="food-results">{foods.map(food=><article key={food.id}><div><strong>{food.name}</strong>{food.brand&&<small>{food.brand}</small>}{food.source&&<small>{food.sourceUrl?<a href={food.sourceUrl} target="_blank" rel="noreferrer">{food.source}</a>:food.source}</small>}<span>{food.calories} קלוריות · {food.proteinG} חלבון · {food.carbsG} פחמימות · {food.fatG} שומן</span></div><button type="button" className="button secondary" onClick={()=>choose(food)}>הוספה <Plus size={16}/></button></article>)}</div></section>;
}
