'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Search,X} from 'lucide-react';
type Product={code:string;name:string;brand:string;servingSize:string;per100g:{calories:number;proteinG:number;carbsG:number;fatG:number}};
type Draft=Record<string,string|number|null>;
const round=(value:number)=>Number(value.toFixed(1));
export function NutritionScanner({today,onProduct}:{today:string;onProduct:(draft:Draft)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),video=useRef<HTMLVideoElement>(null),controls=useRef<{stop:()=>void}|null>(null);
 const [code,setCode]=useState(''),[product,setProduct]=useState<Product|null>(null),[measure,setMeasure]=useState<'grams'|'servings'>('grams'),[amount,setAmount]=useState(100),[servingGrams,setServingGrams]=useState(100),[busy,setBusy]=useState(false),[error,setError]=useState(''),[camera,setCamera]=useState(false);
 function stop(){controls.current?.stop();controls.current=null;if(video.current?.srcObject)(video.current.srcObject as MediaStream).getTracks().forEach(track=>track.stop());setCamera(false);}
 useEffect(()=>()=>stop(),[]);
 async function lookup(raw=code){setBusy(true);setError('');try{const response=await fetch(`/api/nutrition/barcode/${encodeURIComponent(raw)}`),body=await response.json();if(!response.ok)throw new Error(body.error??'לא ניתן לזהות את המוצר.');const found=body as Product,match=found.servingSize.match(/([\d.,]+)\s*g/i);setProduct(found);setServingGrams(match?Number(match[1].replace(',','.')):100);setAmount(match?1:100);setMeasure(match?'servings':'grams');stop();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לזהות את המוצר.');}finally{setBusy(false);}}
 async function startCamera(){setError('');try{stop();setCamera(true);await new Promise(resolve=>setTimeout(resolve,0));if(!video.current)throw new Error('לא ניתן להפעיל את תצוגת המצלמה.');const {BrowserMultiFormatReader}=await import('@zxing/browser'),reader=new BrowserMultiFormatReader();controls.current=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}}},video.current,result=>{if(result){const value=result.getText();setCode(value);controls.current?.stop();void lookup(value);}});}catch(e){stop();setError(e instanceof Error?e.message:'לא ניתן לפתוח את המצלמה.');}}
 function add(){if(!product)return;const grams=measure==='grams'?amount:amount*servingGrams,factor=grams/100;onProduct({name:product.name,meal:'Other',date:today,quantity:grams,unit:measure==='grams'?'גרם':`${amount} מנה`,barcode:product.code,foodKey:`off:${product.code}`,source:'Open Food Facts',calories:Math.round(product.per100g.calories*factor),proteinG:round(product.per100g.proteinG*factor),carbsG:round(product.per100g.carbsG*factor),fatG:round(product.per100g.fatG*factor),preferenceQuantity:amount,preferenceUnit:measure,preferenceServingGrams:servingGrams,preferenceServingName:'מנה'});stop();dialog.current?.close();setProduct(null);}
 return <section className="scanner-panel"><div><Camera size={24}/><div><h2>סריקת מוצר</h2><p>סרוק ברקוד, בחר גרמים או מנות ותקן את הכמות לפי הצורך.</p></div></div><button className="button secondary" onClick={()=>{setProduct(null);dialog.current?.showModal();}}><Camera size={17}/>פתיחת סורק</button>
  <dialog className="modal scanner-modal" ref={dialog} onClick={event=>{const box=event.currentTarget.getBoundingClientRect();if(event.target===event.currentTarget&&(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom))event.currentTarget.close();}} onClose={stop}><div className="modal-heading"><h2>{product?'בחירת כמות':'סריקת ברקוד'}</h2><button className="icon-button" aria-label="סגירה" onClick={()=>dialog.current?.close()}><X size={20}/></button></div>
  {!product?<><p className="module-hint">יש לאפשר גישה למצלמה. אפשר גם להקליד את המספר שמתחת לברקוד.</p><video ref={video} className={`barcode-video ${camera?'':'hidden'}`} playsInline muted/><button className="button secondary full-button" type="button" onClick={startCamera} disabled={busy}><Camera size={17}/>סריקה באמצעות המצלמה</button><label>מספר ברקוד<input inputMode="numeric" pattern="[0-9]{8,14}" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="button primary full-button" disabled={busy||!/^\d{8,14}$/.test(code)} onClick={()=>lookup()}><Search size={17}/>{busy?'מחפש…':'זיהוי והמשך'}</button></>:<><div className="scanned-product"><strong>{product.name}</strong><small>{product.brand}</small></div><div className="measure-toggle"><button className={measure==='grams'?'selected':''} onClick={()=>setMeasure('grams')}>לפי גרמים</button><button className={measure==='servings'?'selected':''} onClick={()=>setMeasure('servings')}>לפי מנה</button></div><div className="serving-fields"><label>{measure==='grams'?'כמות בגרמים':'מספר מנות'}<input type="number" min="0.1" max="10000" step="0.1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>{measure==='servings'&&<label>גרם למנה<input type="number" min="0.1" max="10000" step="0.1" value={servingGrams} onChange={e=>setServingGrams(Number(e.target.value))}/></label>}</div><p className="amount-explanation">הכמות לחישוב: {round(measure==='grams'?amount:amount*servingGrams)} גרם</p><div className="modal-actions"><button className="button secondary" onClick={()=>setProduct(null)}>חזרה</button><button className="button primary" disabled={amount<=0||servingGrams<=0} onClick={add}>הוספה ליומן</button></div></>}{error&&<p className="error-text" role="alert">{error}</p>}</dialog>
 </section>;
}
