'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronLeft, ChevronRight, Plus, Search, Star, Trash2, Pencil, X, SlidersHorizontal } from 'lucide-react';
import { IsraeliDatePicker } from '@/components/israeli-date-picker';
import { NutritionScanner } from '@/components/nutrition-scanner';
import type { NutritionFood } from '@/lib/nutrition-foods';

type Entry={id:string;name:string;date:string;calories:number;proteinG:number;carbsG:number;fatG:number;quantity:number;unit:string;barcode:string;foodKey:string|null;source:string};
type Settings={calorieGoal:number|null;proteinGoalG:number|null;nutritionGoalMode:string;age:number|null;sex:string|null;heightCm:number|null;weightKg:number|null;activityLevel:string|null;weightGoal:string|null};
type PersonalFood=NutritionFood&{rawId:string};
type Draft={name:string;brand?:string;calories:number;proteinG:number;carbsG:number;fatG:number;barcode?:string};
const emptyDraft:Draft={name:'',brand:'',calories:0,proteinG:0,carbsG:0,fatG:0,barcode:''};
const format=(value:number)=>Number(value.toFixed(1)).toLocaleString('he-IL',{maximumFractionDigits:1});
const dayLabel=(date:string,today:string)=>date===today?'היום':new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(`${date}T00:00:00Z`));
async function request(url:string,method='GET',data?:unknown){const response=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const body=await response.json();if(!response.ok)throw new Error(body.error??'לא ניתן להשלים את הפעולה.');return body;}
function shiftDay(value:string,amount:number){const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+amount);return date.toISOString().slice(0,10);}
function backdrop(event:React.MouseEvent<HTMLDialogElement>){const box=event.currentTarget.getBoundingClientRect();if(event.target===event.currentTarget&&(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom))event.currentTarget.close();}

export function NutritionWorkspace({today,entries,settings,personalFoods}:{today:string;entries:Entry[];settings:Settings;personalFoods:PersonalFood[]}){
  const router=useRouter(),addDialog=useRef<HTMLDialogElement>(null),foodDialog=useRef<HTMLDialogElement>(null),goalsDialog=useRef<HTMLDialogElement>(null);
  const [date,setDate]=useState(today),[query,setQuery]=useState(''),[results,setResults]=useState<NutritionFood[]>([]),[selected,setSelected]=useState<NutritionFood|null>(null),[grams,setGrams]=useState(100),[editingEntry,setEditingEntry]=useState<Entry|null>(null),[online,setOnline]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[draft,setDraft]=useState<Draft>(emptyDraft),[editingFood,setEditingFood]=useState<PersonalFood|null>(null),[goalMode,setGoalMode]=useState(settings.nutritionGoalMode||'auto');
  const daily=entries.filter(entry=>entry.date===date),totals=daily.reduce((sum,item)=>({calories:sum.calories+item.calories,proteinG:sum.proteinG+item.proteinG,carbsG:sum.carbsG+item.carbsG,fatG:sum.fatG+item.fatG}),{calories:0,proteinG:0,carbsG:0,fatG:0});
  const scaled=useMemo(()=>selected?{calories:Math.round(selected.calories*grams/100),proteinG:selected.proteinG*grams/100,carbsG:selected.carbsG*grams/100,fatG:selected.fatG*grams/100}:null,[selected,grams]);
  useEffect(()=>{if(query.trim().length<2){setResults(personalFoods);return;}const controller=new AbortController(),timer=window.setTimeout(async()=>{try{const response=await fetch(`/api/nutrition/search?q=${encodeURIComponent(query)}${online?'&online=1':''}`,{signal:controller.signal});const body=await response.json();if(response.ok)setResults(body.foods??[]);}catch(e){if((e as Error).name!=='AbortError')setError('החיפוש אינו זמין כרגע.');}},250);return()=>{window.clearTimeout(timer);controller.abort();};},[query,online,personalFoods]);
  function openAdd(){setQuery('');setResults(personalFoods);setSelected(null);setEditingEntry(null);setGrams(100);setOnline(false);setError('');addDialog.current?.showModal();}
  function editEntry(entry:Entry){const factor=100/entry.quantity;setSelected({id:entry.foodKey??`entry:${entry.id}`,name:entry.name,barcode:entry.barcode,source:entry.source,calories:entry.calories*factor,proteinG:entry.proteinG*factor,carbsG:entry.carbsG*factor,fatG:entry.fatG*factor});setEditingEntry(entry);setGrams(entry.quantity);setError('');addDialog.current?.showModal();}
  async function addEntry(food=selected,amount=grams,override?:Record<string,unknown>){if(!food&&!override)return;setBusy(true);setError('');try{const values=override??{name:food!.name,meal:'Other',date,quantity:amount,unit:'גרם',barcode:food!.barcode??'',foodKey:food!.id.startsWith('entry:')?null:food!.id,source:food!.source,calories:Math.round(food!.calories*amount/100),proteinG:Number((food!.proteinG*amount/100).toFixed(1)),carbsG:Number((food!.carbsG*amount/100).toFixed(1)),fatG:Number((food!.fatG*amount/100).toFixed(1))};await request(`/api/modules/nutrition${editingEntry?`/${editingEntry.id}`:''}`,editingEntry?'PATCH':'POST',values);addDialog.current?.close();setNotice(editingEntry?'הרשומה עודכנה.':'המזון נוסף ליומן.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
  async function removeEntry(id:string){if(!confirm('למחוק את הרשומה מהיומן?'))return;setBusy(true);try{await request(`/api/modules/nutrition/${id}`,'DELETE');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן למחוק.');}finally{setBusy(false);}}
  async function toggleFavorite(food:NutritionFood){try{await request('/api/nutrition/preferences','POST',{foodKey:food.id,favorite:!food.favorite});setResults(current=>current.map(item=>item.id===food.id?{...item,favorite:!item.favorite}:item));router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לעדכן מועדף.');}}
  function editPersonal(food:PersonalFood|null){setEditingFood(food);setDraft(food?{name:food.name,brand:food.brand,calories:food.calories,proteinG:food.proteinG,carbsG:food.carbsG,fatG:food.fatG,barcode:food.barcode}:emptyDraft);setError('');foodDialog.current?.showModal();}
  async function savePersonal(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const data={name:draft.name,brand:draft.brand??'',caloriesPer100:Number(draft.calories),proteinPer100G:Number(draft.proteinG),carbsPer100G:Number(draft.carbsG),fatPer100G:Number(draft.fatG),barcode:draft.barcode??''};await request(`/api/nutrition/foods${editingFood?`/${editingFood.rawId}`:''}`,editingFood?'PATCH':'POST',data);foodDialog.current?.close();setNotice('המזון האישי נשמר.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
  async function saveGoals(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const number=(key:string)=>form.get(key)?Number(form.get(key)):null;const data={nutritionGoalMode:goalMode,age:number('age'),sex:String(form.get('sex')||'')||null,heightCm:number('heightCm'),weightKg:number('weightKg'),activityLevel:String(form.get('activityLevel')||'')||null,weightGoal:String(form.get('weightGoal')||'')||null,...(goalMode==='manual'?{calorieGoal:number('calorieGoal'),proteinGoalG:number('proteinGoalG')}:{})};try{await request('/api/modules/goals','POST',data);goalsDialog.current?.close();setNotice('יעדי התזונה נשמרו.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
  return <main className="module-workspace nutrition-workspace">
    <header className="page-heading nutrition-heading"><div><span className="eyebrow">מעקב תזונה</span><h1>יומן האכילה שלי</h1><p>כל הערכים מחושבים לפי 100 גרם והכמות שאכלת.</p></div><button className="button secondary" onClick={()=>goalsDialog.current?.showModal()}><SlidersHorizontal size={17}/>יעדים</button></header>
    <section className="nutrition-day-nav"><button className="icon-button" aria-label="היום הבא" onClick={()=>setDate(shiftDay(date,1))}><ChevronRight/></button><div><strong>{dayLabel(date,today)}</strong><IsraeliDatePicker label="תאריך היומן" value={date} onChange={value=>value&&setDate(value)}/></div><button className="icon-button" aria-label="היום הקודם" onClick={()=>setDate(shiftDay(date,-1))}><ChevronLeft/></button></section>
    <section className="nutrition-summary" aria-label="סיכום יומי"><div className="calorie-summary"><small>קלוריות</small><strong>{format(totals.calories)}</strong><span>{settings.calorieGoal?`מתוך ${settings.calorieGoal.toLocaleString('he-IL')}`:'ללא יעד'}</span></div>{[{label:'חלבון',value:totals.proteinG,goal:settings.proteinGoalG},{label:'פחמימות',value:totals.carbsG},{label:'שומן',value:totals.fatG}].map(metric=><div key={metric.label}><small>{metric.label}</small><strong>{format(metric.value)}</strong><span>{metric.goal?`מתוך ${metric.goal} גרם`:'גרם'}</span></div>)}</section>
    <div className="nutrition-primary-actions"><button className="button primary" onClick={openAdd}>הוספת מזון <Plus size={17}/></button><button className="button secondary" onClick={()=>editPersonal(null)}>יצירת מזון אישי <Plus size={17}/></button></div>
    <NutritionScanner today={date} onProduct={product=>{setEditingEntry(null);void addEntry(null,Number(product.quantity??100),{...product,foodKey:product.barcode?`off:${product.barcode}`:null,source:'Open Food Facts'});}}/>
    <section className="journal-panel nutrition-diary"><div className="section-heading"><div><h2>מה אכלתי</h2><p>{daily.length} רשומות בתאריך הנבחר</p></div></div>{notice&&<p className="feedback" role="status">{notice}</p>}{error&&!addDialog.current?.open&&!foodDialog.current?.open&&!goalsDialog.current?.open&&<p className="error-text">{error}</p>}{daily.length?<div className="nutrition-entry-list">{daily.map(entry=><article key={entry.id}><div><h3>{entry.name}</h3><p>{format(entry.quantity)} גרם · {format(entry.calories)} קל׳</p></div><div className="entry-macros"><span>חלבון <b>{format(entry.proteinG)}</b></span><span>פחמימות <b>{format(entry.carbsG)}</b></span><span>שומן <b>{format(entry.fatG)}</b></span></div><div className="nutrition-row-actions"><button className="icon-button" aria-label={`עריכת ${entry.name}`} onClick={()=>editEntry(entry)}><Pencil size={17}/></button><button className="icon-button" aria-label={`מחיקת ${entry.name}`} disabled={busy} onClick={()=>void removeEntry(entry.id)}><Trash2 size={17}/></button></div></article>)}</div>:<p className="journal-empty">עדיין לא הוספת מזון ליום הזה.</p>}</section>
    <section className="journal-panel personal-foods"><div className="section-heading"><div><h2>המאגר האישי שלי</h2><p>ערכים קבועים ל־100 גרם</p></div></div>{personalFoods.length?<div className="personal-food-list">{personalFoods.map(food=><article key={food.id}><div><strong>{food.name}</strong><small>{food.calories} קל׳ · {format(food.proteinG)} גרם חלבון</small></div><button className="icon-button" aria-label={`עריכת ${food.name}`} onClick={()=>editPersonal(food)}><Pencil size={16}/></button><button className="icon-button" aria-label={`מחיקת ${food.name}`} onClick={async()=>{if(confirm('למחוק את המזון מהמאגר האישי? רשומות היומן יישארו ללא שינוי.')){await request(`/api/nutrition/foods/${food.rawId}`,'DELETE');router.refresh();}}}><Trash2 size={16}/></button></article>)}</div>:<p className="journal-empty">מזונות שתיצור יישמרו כאן לשימוש חוזר.</p>}</section>
    <dialog ref={addDialog} className="modal nutrition-add-modal" onClick={backdrop}><div className="modal-heading"><div><span className="eyebrow">הוספה ליומן</span><h2>בחירת מזון</h2></div><button className="icon-button" aria-label="סגירה" onClick={()=>addDialog.current?.close()}><X/></button></div><label className="search-field"><Search size={18}/><input autoFocus placeholder="חיפוש מזון בעברית…" value={query} onChange={e=>{setQuery(e.target.value);setOnline(false);}}/></label>{!selected?<><div className="nutrition-results">{results.map(food=><article key={food.id}><button className="food-result-main" onClick={()=>setSelected(food)}><strong>{food.name}</strong><small>{food.brand&&`${food.brand} · `}{food.source}</small><span>{food.calories} קל׳ · חלבון {format(food.proteinG)} · פחמימות {format(food.carbsG)} · שומן {format(food.fatG)}</span></button><button className={`icon-button ${food.favorite?'is-favorite':''}`} aria-label={food.favorite?'הסרה מהמועדפים':'הוספה למועדפים'} onClick={()=>void toggleFavorite(food)}><Star size={17} fill={food.favorite?'currentColor':'none'}/></button></article>)}</div>{query.trim().length>=2&&!online&&<button className="button secondary full-button" onClick={()=>setOnline(true)}>חיפוש גם ב־USDA ובמוצרים ארוזים</button>}<button className="button ghost full-button" onClick={()=>{addDialog.current?.close();editPersonal(null);}}>לא מצאת? יצירת מזון אישי <Plus size={16}/></button></>:<><button className="selected-food" onClick={()=>setSelected(null)}><strong>{selected.name}</strong><small>שינוי בחירה</small></button><label>כמות שאכלת (גרם)<input type="number" min="1" max="10000" value={grams} onChange={e=>setGrams(Math.max(1,Number(e.target.value)||1))}/></label>{scaled&&<div className="nutrition-preview"><span><b>{scaled.calories}</b> קלוריות</span><span><b>{format(scaled.proteinG)}</b> חלבון</span><span><b>{format(scaled.carbsG)}</b> פחמימות</span><span><b>{format(scaled.fatG)}</b> שומן</span></div>}<div className="modal-actions"><button className="button secondary" onClick={()=>setSelected(null)}>חזרה</button><button className="button primary" disabled={busy} onClick={()=>void addEntry()}>{busy?'שומר…':'הוספה ליומן'}</button></div></>}{error&&<p className="error-text">{error}</p>}</dialog>
    <dialog ref={foodDialog} className="modal nutrition-food-modal" onClick={backdrop}><form onSubmit={savePersonal}><div className="modal-heading"><h2>{editingFood?'עריכת מזון אישי':'יצירת מזון אישי'}</h2><button type="button" className="icon-button" aria-label="סגירה" onClick={()=>foodDialog.current?.close()}><X/></button></div><p className="module-hint">הזן ערכים עבור 100 גרם. בזמן ההוספה ליומן תבחר את הכמות שאכלת.</p><div className="form-grid"><label className="wide-field">שם המזון<input required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>מותג <span className="optional">(לא חובה)</span><input maxLength={120} value={draft.brand} onChange={e=>setDraft({...draft,brand:e.target.value})}/></label><label>קלוריות<input required type="number" min="0" max="10000" value={draft.calories} onChange={e=>setDraft({...draft,calories:Number(e.target.value)})}/></label><label>חלבון (גרם)<input required type="number" min="0" max="1000" step="0.1" value={draft.proteinG} onChange={e=>setDraft({...draft,proteinG:Number(e.target.value)})}/></label><label>פחמימות (גרם)<input required type="number" min="0" max="1000" step="0.1" value={draft.carbsG} onChange={e=>setDraft({...draft,carbsG:Number(e.target.value)})}/></label><label>שומן (גרם)<input required type="number" min="0" max="1000" step="0.1" value={draft.fatG} onChange={e=>setDraft({...draft,fatG:Number(e.target.value)})}/></label><label>ברקוד <span className="optional">(לא חובה)</span><input inputMode="numeric" pattern="[0-9]{8,14}" value={draft.barcode} onChange={e=>setDraft({...draft,barcode:e.target.value.replace(/\D/g,'')})}/></label></div>{error&&<p className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>foodDialog.current?.close()}>ביטול</button><button className="button primary" disabled={busy}>{busy?'שומר…':'שמירת המזון'}</button></div></form></dialog>
    <dialog ref={goalsDialog} className="modal nutrition-goals-modal" onClick={backdrop}><form onSubmit={saveGoals}><div className="modal-heading"><h2>יעדי תזונה</h2><button type="button" className="icon-button" aria-label="סגירה" onClick={()=>goalsDialog.current?.close()}><X/></button></div><div className="goal-mode"><button type="button" className={goalMode==='auto'?'selected':''} onClick={()=>setGoalMode('auto')}>חישוב אוטומטי</button><button type="button" className={goalMode==='manual'?'selected':''} onClick={()=>setGoalMode('manual')}>שינוי ידני</button></div><div className="form-grid"><label>גיל<input name="age" type="number" min="13" max="120" defaultValue={settings.age??''}/></label><label>מין לחישוב<select name="sex" defaultValue={settings.sex??''}><option value="">בחירה</option><option value="male">זכר</option><option value="female">נקבה</option></select></label><label>גובה (ס״מ)<input name="heightCm" type="number" min="100" max="250" defaultValue={settings.heightCm??''}/></label><label>משקל (ק״ג)<input name="weightKg" type="number" min="30" max="400" step="0.1" defaultValue={settings.weightKg??''}/></label><label>רמת פעילות<select name="activityLevel" defaultValue={settings.activityLevel??''}><option value="">בחירה</option><option value="sedentary">מעטה</option><option value="light">קלה</option><option value="moderate">בינונית</option><option value="active">גבוהה</option><option value="very_active">גבוהה מאוד</option></select></label><label>מטרה<select name="weightGoal" defaultValue={settings.weightGoal??''}><option value="">בחירה</option><option value="lose">ירידה במשקל</option><option value="maintain">שמירה</option><option value="gain">עלייה / מסה</option></select></label>{goalMode==='manual'&&<><label>יעד קלוריות<input required name="calorieGoal" type="number" min="1" max="20000" defaultValue={settings.calorieGoal??''}/></label><label>יעד חלבון (גרם)<input required name="proteinGoalG" type="number" min="1" max="2000" defaultValue={settings.proteinGoalG??''}/></label></>}</div>{error&&<p className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>goalsDialog.current?.close()}>ביטול</button><button className="button primary" disabled={busy}>{busy?'שומר…':'שמירת יעדים'}</button></div></form></dialog>
  </main>;
}
