'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Bell,ChevronLeft,ChevronRight,Dumbbell,FlaskConical,LibraryBig,Pencil,Plus,Search,SlidersHorizontal,Star,Trash2,X} from 'lucide-react';
import {IsraeliDatePicker} from '@/components/israeli-date-picker';
import {NutritionScanner} from '@/components/nutrition-scanner';
import type {NutritionFood} from '@/lib/nutrition-foods';
type Entry={id:string;name:string;meal:string;date:string;calories:number;proteinG:number;carbsG:number;fatG:number;quantity:number;unit:string;barcode:string;foodKey:string|null;source:string};
type Settings={calorieGoal:number|null;proteinGoalG:number|null;nutritionGoalMode:string;age:number|null;sex:string|null;heightCm:number|null;weightKg:number|null;weeklyWorkouts:number|null;weightGoal:string|null;creatineReminderEnabled:boolean;creatineReminderTime:string};
type PersonalFood=NutritionFood&{rawId:string};
type ScannerDraft={name:string;meal:string;date:string;quantity:number;unit:string;barcode:string;foodKey:string;source:string;calories:number;proteinG:number;carbsG:number;fatG:number;preferenceQuantity:number;preferenceUnit:'grams'|'servings';preferenceServingGrams:number;preferenceServingName:string};
const fmt=(v:number)=>Number(v.toFixed(1)).toLocaleString('he-IL',{maximumFractionDigits:1});
const mealLabels:Record<string,string>={Breakfast:'ארוחת בוקר',Lunch:'ארוחת צהריים',Dinner:'ארוחת ערב',Snack:'נשנושים',Other:'ללא שיוך'};
const mealOrder=['Breakfast','Lunch','Dinner','Snack','Other'];
async function request(url:string,method='GET',data?:unknown){const response=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const body=await response.json();if(!response.ok)throw new Error(body.error??'לא ניתן להשלים את הפעולה.');return body;}
function shiftDay(value:string,amount:number){const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+amount);return date.toISOString().slice(0,10);}
function backdrop(event:React.MouseEvent<HTMLDialogElement>){const box=event.currentTarget.getBoundingClientRect();if(event.target===event.currentTarget&&(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom))event.currentTarget.close();}
function decodeKey(value:string){const padding='='.repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));}
export function NutritionWorkspace({today,entries,settings,personalFoods}:{today:string;entries:Entry[];settings:Settings;personalFoods:PersonalFood[]}){
 const router=useRouter(),addDialog=useRef<HTMLDialogElement>(null),goalsDialog=useRef<HTMLDialogElement>(null),proteinDialog=useRef<HTMLDialogElement>(null),touchStart=useRef<number|null>(null);
 const [date,setDate]=useState(today),[meal,setMeal]=useState('Other'),[query,setQuery]=useState(''),[results,setResults]=useState<NutritionFood[]>([]),[selected,setSelected]=useState<NutritionFood|null>(null),[amount,setAmount]=useState(100),[measure,setMeasure]=useState<'grams'|'servings'>('grams'),[servingGrams,setServingGrams]=useState(100),[servingName,setServingName]=useState('מנה'),[editingEntry,setEditingEntry]=useState<Entry|null>(null),[online,setOnline]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[goalMode,setGoalMode]=useState(settings.nutritionGoalMode||'auto');
 const [creatineEnabled,setCreatineEnabled]=useState(settings.creatineReminderEnabled),[creatineTime,setCreatineTime]=useState(settings.creatineReminderTime),[deviceReady,setDeviceReady]=useState(false);
 const [scoops,setScoops]=useState(1),[scoopGrams,setScoopGrams]=useState(25),[scoopCalories,setScoopCalories]=useState(100),[scoopProtein,setScoopProtein]=useState(20),[scoopCarbs,setScoopCarbs]=useState(2),[scoopFat,setScoopFat]=useState(1.5);
 const daily=entries.filter(entry=>entry.date===date),mealGroups=mealOrder.map(key=>({key,label:mealLabels[key],entries:daily.filter(entry=>(entry.meal||'Other')===key)})).filter(group=>group.entries.length),totals=daily.reduce((sum,item)=>({calories:sum.calories+item.calories,proteinG:sum.proteinG+item.proteinG,carbsG:sum.carbsG+item.carbsG,fatG:sum.fatG+item.fatG}),{calories:0,proteinG:0,carbsG:0,fatG:0}),actualGrams=measure==='grams'?amount:amount*servingGrams;
 const scaled=useMemo(()=>selected?{calories:Math.round(selected.calories*actualGrams/100),proteinG:selected.proteinG*actualGrams/100,carbsG:selected.carbsG*actualGrams/100,fatG:selected.fatG*actualGrams/100}:null,[selected,actualGrams]);
 useEffect(()=>{if(query.trim().length<2){setResults(personalFoods);return;}const controller=new AbortController(),timer=window.setTimeout(async()=>{try{const response=await fetch(`/api/nutrition/search?q=${encodeURIComponent(query)}${online?'&online=1':''}`,{signal:controller.signal});const body=await response.json();if(response.ok)setResults(body.foods??[]);}catch(e){if((e as Error).name!=='AbortError')setError('החיפוש אינו זמין כרגע.');}},250);return()=>{clearTimeout(timer);controller.abort();};},[query,online,personalFoods]);
 useEffect(()=>{let active=true;(async()=>{if(!('serviceWorker'in navigator)||!('PushManager'in window))return;const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(active)setDeviceReady(Boolean(subscription)&&Notification.permission==='granted');})().catch(()=>{});return()=>{active=false;};},[]);
 function chooseFood(food:NutritionFood){const unit=food.lastUnit??'grams';setSelected(food);setMeasure(unit);setServingGrams(food.servingGrams??100);setServingName(food.servingName??'מנה');setAmount(food.lastQuantity??(unit==='servings'?1:100));}
 function openAdd(){setQuery('');setResults(personalFoods);setSelected(null);setEditingEntry(null);setAmount(100);setMeasure('grams');setServingGrams(100);setServingName('מנה');setOnline(false);setError('');addDialog.current?.showModal();}
 function editEntry(entry:Entry){const factor=100/entry.quantity;setSelected({id:entry.foodKey??`entry:${entry.id}`,name:entry.name,barcode:entry.barcode,source:entry.source,calories:entry.calories*factor,proteinG:entry.proteinG*factor,carbsG:entry.carbsG*factor,fatG:entry.fatG*factor});setEditingEntry(entry);setMeal(entry.meal||'Other');setAmount(entry.quantity);setMeasure('grams');setServingGrams(100);setServingName('מנה');setError('');addDialog.current?.showModal();}
 async function addEntry(){if(!selected||!scaled)return;setBusy(true);setError('');try{await request(`/api/modules/nutrition${editingEntry?`/${editingEntry.id}`:''}`,editingEntry?'PATCH':'POST',{name:selected.name,meal,date,quantity:actualGrams,unit:measure==='grams'?'גרם':`${fmt(amount)} ${servingName}`,barcode:selected.barcode??'',foodKey:selected.id.startsWith('entry:')?null:selected.id,source:selected.source,calories:scaled.calories,proteinG:Number(scaled.proteinG.toFixed(1)),carbsG:Number(scaled.carbsG.toFixed(1)),fatG:Number(scaled.fatG.toFixed(1)),preferenceQuantity:amount,preferenceUnit:measure,preferenceServingGrams:servingGrams,preferenceServingName:servingName});addDialog.current?.close();setNotice(editingEntry?'הרשומה עודכנה.':'המזון נוסף ליומן.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
 async function addScannerProduct(product:ScannerDraft){setBusy(true);setError('');try{await request('/api/modules/nutrition','POST',{...product,date});setNotice('המוצר נוסף ליומן.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור את המוצר.');}finally{setBusy(false);}}
 async function addProtein(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await request('/api/modules/nutrition','POST',{name:'אבקת חלבון',meal:'Other',date,quantity:scoops*scoopGrams,unit:`${fmt(scoops)} סקופ`,barcode:'',foodKey:'quick:protein-powder',source:'SBO',calories:Math.round(scoopCalories*scoops),proteinG:Number((scoopProtein*scoops).toFixed(1)),carbsG:Number((scoopCarbs*scoops).toFixed(1)),fatG:Number((scoopFat*scoops).toFixed(1)),preferenceQuantity:scoops,preferenceUnit:'servings',preferenceServingGrams:scoopGrams,preferenceServingName:'סקופ'});proteinDialog.current?.close();setNotice('אבקת החלבון נוספה ליומן.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
 async function removeEntry(id:string){if(!confirm('למחוק את הרשומה מהיומן?'))return;setBusy(true);try{await request(`/api/modules/nutrition/${id}`,'DELETE');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן למחוק.');}finally{setBusy(false);}}
 async function toggleFavorite(food:NutritionFood){try{await request('/api/nutrition/preferences','POST',{foodKey:food.id,favorite:!food.favorite});setResults(current=>current.map(item=>item.id===food.id?{...item,favorite:!item.favorite}:item));router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לעדכן מועדף.');}}
 async function saveGoals(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget),number=(key:string)=>form.get(key)!==''?Number(form.get(key)):null;try{await request('/api/modules/goals','POST',{nutritionGoalMode:goalMode,age:number('age'),sex:String(form.get('sex')||'')||null,heightCm:number('heightCm'),weightKg:number('weightKg'),weeklyWorkouts:number('weeklyWorkouts'),weightGoal:String(form.get('weightGoal')||'')||null,...(goalMode==='manual'?{calorieGoal:number('calorieGoal'),proteinGoalG:number('proteinGoalG')}:{})});goalsDialog.current?.close();setNotice('יעדי התזונה נשמרו.');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
 async function enableDevice(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('הדפדפן הזה אינו תומך בהתראות Push.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('לא ניתנה הרשאה להתראות.');const registration=await navigator.serviceWorker.ready,existing=await registration.pushManager.getSubscription(),config=await fetch('/api/push/subscriptions').then(response=>response.json());if(!config.publicKey)throw new Error('שירות ההתראות עדיין לא הוגדר בשרת.');const subscription=existing??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(config.publicKey)}),response=await fetch('/api/push/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(subscription.toJSON())});if(!response.ok)throw new Error('לא ניתן לשמור את המכשיר להתראות.');setDeviceReady(true);}
 async function saveCreatine(next=creatineEnabled){setBusy(true);setError('');try{if(next&&!deviceReady)await enableDevice();await request('/api/modules/creatine-reminders','POST',{enabled:next,time:creatineTime});setCreatineEnabled(next);setNotice(next?'תזכורת הקראטין נשמרה.':'תזכורת הקראטין כובתה.');}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור את התזכורת.');}finally{setBusy(false);}}
 return <main className="module-workspace nutrition-workspace">
  <header className="page-heading nutrition-heading"><div><span className="eyebrow">מעקב תזונה</span><h1>יומן האכילה שלי</h1><p>בחר גרמים או מנות, והחישוב יתעדכן לפי מה שאכלת.</p></div><button className="button secondary" onClick={()=>goalsDialog.current?.showModal()}><SlidersHorizontal size={17}/>יעדים</button></header>
  <section className="nutrition-day-nav" onTouchStart={event=>touchStart.current=event.touches[0].clientX} onTouchEnd={event=>{if(touchStart.current===null)return;const delta=event.changedTouches[0].clientX-touchStart.current;if(Math.abs(delta)>55)setDate(shiftDay(date,delta>0?-1:1));touchStart.current=null;}}><button className="icon-button" aria-label="היום הבא" onClick={()=>setDate(shiftDay(date,1))}><ChevronRight/></button><div><strong>{date===today?'היום':new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(`${date}T00:00:00Z`))}</strong><IsraeliDatePicker label="תאריך היומן" value={date} onChange={value=>value&&setDate(value)}/></div><button className="icon-button" aria-label="היום הקודם" onClick={()=>setDate(shiftDay(date,-1))}><ChevronLeft/></button></section>
  <section className="nutrition-summary" aria-label="סיכום יומי"><div className="calorie-summary"><small>קלוריות</small><strong>{fmt(totals.calories)}</strong><span>{settings.calorieGoal?`מתוך ${settings.calorieGoal.toLocaleString('he-IL')}`:'ללא יעד'}</span></div>{[{label:'חלבון',value:totals.proteinG,goal:settings.proteinGoalG},{label:'פחמימות',value:totals.carbsG},{label:'שומן',value:totals.fatG}].map(metric=><div key={metric.label}><small>{metric.label}</small><strong>{fmt(metric.value)}</strong><span>{metric.goal?`מתוך ${metric.goal} גרם`:'גרם'}</span></div>)}</section>
  <label className="meal-selector">שיוך לארוחה <span className="optional">(לא חובה)</span><select value={meal} onChange={event=>setMeal(event.target.value)}><option value="Other">ללא שיוך</option><option value="Breakfast">ארוחת בוקר</option><option value="Lunch">ארוחת צהריים</option><option value="Dinner">ארוחת ערב</option><option value="Snack">נשנושים</option></select></label><section className="nutrition-primary-actions"><button className="button primary" onClick={openAdd}>הוספת מזון <Plus size={18}/></button><button className="button protein-action" onClick={()=>proteinDialog.current?.showModal()}>אבקת חלבון <Dumbbell size={18}/></button><Link className="button secondary" href="/nutrition/foods">המאגר האישי <LibraryBig size={18}/></Link></section>
  {notice&&<p className="feedback" role="status">{notice}</p>}{error&&<p className="error-text" role="alert">{error}</p>}
  <NutritionScanner today={date} onProduct={product=>void addScannerProduct(product as ScannerDraft)}/>
  <section className="creatine-card"><div><FlaskConical/><span><strong>תזכורת קראטין יומית</strong><small>התראה אחת בכל יום בשעה שתבחר</small></span></div><label>שעה<input type="time" value={creatineTime} onChange={event=>setCreatineTime(event.target.value)}/></label><label className="water-reminder-toggle"><span>{creatineEnabled?'פעילה':'כבויה'}</span><input type="checkbox" checked={creatineEnabled} disabled={busy} onChange={event=>void saveCreatine(event.target.checked)}/><i/></label><button className="button secondary" disabled={busy} onClick={()=>void saveCreatine()}><Bell size={16}/>שמירת התזכורת</button></section>
  <section className="journal-panel nutrition-diary"><div className="section-heading"><div><h2>מה אכלתי</h2><p>{daily.length?`${daily.length} רשומות ביום הזה`:'עדיין לא נוספו מזונות'}</p></div></div>{daily.length?<div className="meal-groups">{mealGroups.map(group=><details open key={group.key}><summary>{group.label}<span>{group.entries.length}</span></summary><div className="nutrition-entry-list">{group.entries.map(entry=><article key={entry.id}><div><h3>{entry.name}</h3><p>{fmt(entry.quantity)} גרם{entry.unit!=='גרם'?` · ${entry.unit}`:''} · {entry.calories} קל׳</p></div><div className="entry-macros"><span><b>{fmt(entry.proteinG)}</b>חלבון</span><span><b>{fmt(entry.carbsG)}</b>פחמימות</span><span><b>{fmt(entry.fatG)}</b>שומן</span></div><div className="nutrition-row-actions"><button className="icon-button" aria-label={`עריכת ${entry.name}`} onClick={()=>editEntry(entry)}><Pencil size={16}/></button><button className="icon-button" aria-label={`מחיקת ${entry.name}`} onClick={()=>void removeEntry(entry.id)}><Trash2 size={16}/></button></div></article>)}</div></details>)}</div>:<p className="journal-empty">אפשר להתחיל בהוספת מזון, אבקת חלבון או סריקת ברקוד.</p>}</section>
  <dialog ref={addDialog} className="modal nutrition-add-modal" onClick={backdrop}><div className="modal-heading"><h2>{editingEntry?'עריכת רשומה':'הוספת מזון'}</h2><button className="icon-button" aria-label="סגירה" onClick={()=>addDialog.current?.close()}><X/></button></div>{!selected?<><label className="search-field"><Search size={18}/><input autoFocus placeholder="חיפוש במאגר משרד הבריאות ובמאגר האישי" value={query} onChange={event=>setQuery(event.target.value)}/></label><label className="online-search"><input type="checkbox" checked={online} onChange={event=>setOnline(event.target.checked)}/>חיפוש משלים גם ב־USDA וב־Open Food Facts</label><div className="nutrition-results">{results.map(food=><article key={food.id}><button className="food-result-main" onClick={()=>chooseFood(food)}><strong>{food.name}</strong><small>{food.source}</small><span>{food.calories} קל׳ · {fmt(food.proteinG)} חלבון ל־100 גרם</span></button><button className={`icon-button ${food.favorite?'is-favorite':''}`} aria-label="מועדף" onClick={()=>void toggleFavorite(food)}><Star size={17}/></button></article>)}</div></>:<><button className="selected-food" onClick={()=>!editingEntry&&setSelected(null)}><strong>{selected.name}</strong><small>{selected.source} · ערכים ל־100 גרם</small></button><div className="measure-toggle"><button className={measure==='grams'?'selected':''} onClick={()=>setMeasure('grams')}>לפי גרמים</button><button className={measure==='servings'?'selected':''} onClick={()=>setMeasure('servings')}>לפי כמות / מנה</button></div><div className="serving-fields"><label>{measure==='grams'?'כמות שאכלת (גרם)':'מספר מנות'}<input type="number" min="0.1" max="10000" step="0.1" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label>{measure==='servings'&&<><label>שם המנה<input value={servingName} maxLength={40} onChange={event=>setServingName(event.target.value)}/></label><label>גרם למנה<input type="number" min="0.1" max="10000" step="0.1" value={servingGrams} onChange={event=>setServingGrams(Number(event.target.value))}/></label></>}</div>{measure==='servings'&&<p className="amount-explanation">סה״כ {fmt(actualGrams)} גרם. אפשר לתקן את משקל המנה לפני השמירה.</p>}<div className="nutrition-preview">{scaled&&Object.entries({קלוריות:scaled.calories,חלבון:scaled.proteinG,פחמימות:scaled.carbsG,שומן:scaled.fatG}).map(([label,value])=><span key={label}><b>{fmt(value)}</b>{label}</span>)}</div><div className="modal-actions"><button className="button secondary" onClick={()=>addDialog.current?.close()}>ביטול</button><button className="button primary" disabled={busy||amount<=0||servingGrams<=0} onClick={()=>void addEntry()}>{busy?'שומר…':'הוספה ליומן'}</button></div></>}</dialog>
  <dialog ref={proteinDialog} className="modal protein-modal" onClick={backdrop}><form onSubmit={addProtein}><div className="modal-heading"><h2>הוספת אבקת חלבון</h2><button type="button" className="icon-button" aria-label="סגירה" onClick={()=>proteinDialog.current?.close()}><X/></button></div><p className="module-hint">התחלנו מסקופ ממוצע של 25 גרם. כל הערכים ניתנים לתיקון.</p><div className="form-grid">{[['מספר סקופים',scoops,setScoops,0.1,20],['גרם בסקופ',scoopGrams,setScoopGrams,1,200],['קלוריות לסקופ',scoopCalories,setScoopCalories,0,2000],['חלבון לסקופ',scoopProtein,setScoopProtein,0,200],['פחמימות לסקופ',scoopCarbs,setScoopCarbs,0,200],['שומן לסקופ',scoopFat,setScoopFat,0,200]].map(([label,value,setter,min,max])=><label key={String(label)}>{String(label)}<input type="number" min={Number(min)} max={Number(max)} step="0.1" value={Number(value)} onChange={e=>(setter as React.Dispatch<React.SetStateAction<number>>)(Number(e.target.value))}/></label>)}</div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>proteinDialog.current?.close()}>ביטול</button><button className="button primary" disabled={busy}>{busy?'שומר…':'הוספה ליומן'}</button></div></form></dialog>
  <dialog ref={goalsDialog} className="modal nutrition-goals-modal" onClick={backdrop}><form onSubmit={saveGoals}><div className="modal-heading"><h2>יעדי תזונה</h2><button type="button" className="icon-button" aria-label="סגירה" onClick={()=>goalsDialog.current?.close()}><X/></button></div><div className="goal-mode"><button type="button" className={goalMode==='auto'?'selected':''} onClick={()=>setGoalMode('auto')}>חישוב אוטומטי</button><button type="button" className={goalMode==='manual'?'selected':''} onClick={()=>setGoalMode('manual')}>שינוי ידני</button></div><div className="form-grid"><label>גיל<input name="age" type="number" min="13" max="120" defaultValue={settings.age??''}/></label><label>מין לחישוב<select name="sex" defaultValue={settings.sex??''}><option value="">בחירה</option><option value="male">זכר</option><option value="female">נקבה</option></select></label><label>גובה (ס״מ)<input name="heightCm" type="number" min="100" max="250" defaultValue={settings.heightCm??''}/></label><label>משקל (ק״ג)<input name="weightKg" type="number" min="30" max="400" step="0.1" defaultValue={settings.weightKg??''}/></label><label>אימונים בשבוע<select name="weeklyWorkouts" defaultValue={settings.weeklyWorkouts??''}><option value="">בחירה</option>{[0,1,2,3,4,5].map(value=><option key={value} value={value}>{value} אימונים</option>)}</select></label><label>מטרה<select name="weightGoal" defaultValue={settings.weightGoal??''}><option value="">בחירה</option><option value="lose">ירידה במשקל</option><option value="maintain">שמירה</option><option value="gain">עלייה / מסה</option></select></label>{goalMode==='manual'&&<><label>יעד קלוריות<input required name="calorieGoal" type="number" min="1" max="20000" defaultValue={settings.calorieGoal??''}/></label><label>יעד חלבון (גרם)<input required name="proteinGoalG" type="number" min="1" max="2000" defaultValue={settings.proteinGoalG??''}/></label></>}</div>{error&&<p className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>goalsDialog.current?.close()}>ביטול</button><button className="button primary" disabled={busy}>{busy?'שומר…':'שמירת יעדים'}</button></div></form></dialog>
 </main>;
}
