'use client';
import Link from 'next/link';
import {useMemo,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,LibraryBig,Pencil,Plus,Search,Trash2,X} from 'lucide-react';
type Food={id:string;name:string;brand:string;barcode:string;servingName:string;servingGrams:number;calories:number;proteinG:number;carbsG:number;fatG:number};
const blank:Omit<Food,'id'>={name:'',brand:'',barcode:'',servingName:'מנה',servingGrams:100,calories:0,proteinG:0,carbsG:0,fatG:0};
async function request(url:string,method:string,data?:unknown){const response=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined}),body=await response.json();if(!response.ok)throw new Error(body.error??'לא ניתן להשלים את הפעולה.');}
function backdrop(event:React.MouseEvent<HTMLDialogElement>){const box=event.currentTarget.getBoundingClientRect();if(event.target===event.currentTarget&&(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom))event.currentTarget.close();}
export function PersonalFoodsWorkspace({foods}:{foods:Food[]}){const router=useRouter(),dialog=useRef<HTMLDialogElement>(null),[query,setQuery]=useState(''),[draft,setDraft]=useState(blank),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const shown=useMemo(()=>foods.filter(food=>`${food.name} ${food.brand}`.toLowerCase().includes(query.toLowerCase())),[foods,query]);
 function open(food?:Food){setEditing(food?.id??null);setDraft(food?{name:food.name,brand:food.brand,barcode:food.barcode,servingName:food.servingName,servingGrams:food.servingGrams,calories:food.calories,proteinG:food.proteinG,carbsG:food.carbsG,fatG:food.fatG}:blank);setError('');dialog.current?.showModal();}
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await request(`/api/nutrition/foods${editing?`/${editing}`:''}`,editing?'PATCH':'POST',{name:draft.name,brand:draft.brand,barcode:draft.barcode,servingName:draft.servingName,servingGrams:Number(draft.servingGrams),caloriesPer100:Number(draft.calories),proteinPer100G:Number(draft.proteinG),carbsPer100G:Number(draft.carbsG),fatPer100G:Number(draft.fatG)});dialog.current?.close();router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
 async function remove(food:Food){if(!confirm(`למחוק את ${food.name} מהמאגר האישי?`))return;setBusy(true);try{await request(`/api/nutrition/foods/${food.id}`,'DELETE');router.refresh();}catch(e){setError(e instanceof Error?e.message:'לא ניתן למחוק.');}finally{setBusy(false);}}
 return <main className="module-workspace personal-foods-workspace"><header className="page-heading personal-food-heading"><div><span className="eyebrow">מעקב תזונה</span><h1>המאגר האישי שלי</h1><p>מזונות שיצרת נשמרים רק בחשבון שלך וזמינים מיד ביומן.</p></div><Link className="button secondary" href="/nutrition"><ArrowRight size={17}/>חזרה ליומן</Link></header><section className="personal-food-toolbar"><label className="search-field"><Search size={18}/><input placeholder="חיפוש במאגר האישי" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="button primary" onClick={()=>open()}>יצירת מזון <Plus size={18}/></button></section>{error&&<p className="error-text">{error}</p>}<section className="personal-food-cards">{shown.map(food=><article key={food.id}><div className="personal-food-icon"><LibraryBig/></div><div><h2>{food.name}</h2><p>{food.brand||'ללא מותג'} · מנה: {food.servingGrams} גרם</p><div className="food-macro-line"><span>{food.calories} קל׳</span><span>{food.proteinG} חלבון</span><span>{food.carbsG} פחמימות</span><span>{food.fatG} שומן</span></div></div><div className="card-actions"><button className="icon-button" aria-label={`עריכת ${food.name}`} onClick={()=>open(food)}><Pencil size={17}/></button><button className="icon-button" aria-label={`מחיקת ${food.name}`} disabled={busy} onClick={()=>void remove(food)}><Trash2 size={17}/></button></div></article>)}</section>{!shown.length&&<section className="journal-panel journal-empty">{query?'לא נמצאו מזונות מתאימים.':'עוד לא יצרת מזון אישי. לחץ על יצירת מזון כדי להתחיל.'}</section>}
 <dialog ref={dialog} className="modal nutrition-food-modal improved-food-modal" onClick={backdrop}><form onSubmit={save}><div className="modal-heading"><div><span className="eyebrow">המאגר האישי</span><h2>{editing?'עריכת מזון':'יצירת מזון חדש'}</h2></div><button type="button" className="icon-button" aria-label="סגירה" onClick={()=>dialog.current?.close()}><X/></button></div><fieldset><legend>פרטי המזון</legend><div className="form-grid"><label>שם המזון<input required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>מותג (לא חובה)<input maxLength={120} value={draft.brand} onChange={e=>setDraft({...draft,brand:e.target.value})}/></label><label className="wide-field">ברקוד (לא חובה)<input inputMode="numeric" pattern="[0-9]{8,14}" value={draft.barcode} onChange={e=>setDraft({...draft,barcode:e.target.value.replace(/\D/g,'')})}/></label></div></fieldset><fieldset><legend>מנה ויחידה</legend><div className="form-grid"><label>שם המנה<input required maxLength={40} value={draft.servingName} onChange={e=>setDraft({...draft,servingName:e.target.value})}/></label><label>משקל מנה בגרם<input required type="number" min="0.1" max="10000" step="0.1" value={draft.servingGrams} onChange={e=>setDraft({...draft,servingGrams:Number(e.target.value)})}/></label></div></fieldset><fieldset><legend>ערכים ל־100 גרם</legend><div className="form-grid macro-input-grid">{([['קלוריות','calories'],['חלבון','proteinG'],['פחמימות','carbsG'],['שומן','fatG']] as const).map(([label,key])=><label key={key}>{label}<input required type="number" min="0" max="10000" step={key==='calories'?'1':'0.1'} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}</div></fieldset>{error&&<p className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>dialog.current?.close()}>ביטול</button><button className="button primary" disabled={busy}>{busy?'שומר…':'שמירת המזון'}</button></div></form></dialog></main>;
}
