'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {BriefcaseBusiness,Clock3,CalendarDays,ChartColumn,Wallet,Plane,Receipt,FileText,FolderOpen,Plus,X,Settings,Pencil,Trash2,Download,Camera,Coffee,Home,MapPin,ChevronRight,ChevronLeft} from 'lucide-react';
import {TimePicker} from './time-picker';
import {IsraeliDatePicker} from './israeli-date-picker';
import {dayKey,monthDays,monthSummary,shiftMinutes,workClock,workTypes,type WorkData,type WorkEntryRow,type WorkTripRow,type WorkExpenseRow} from '@/lib/work-calculations';
import {reportRows} from '@/lib/work-export-client';
type Values=Record<string,string|number|boolean|null>;
type Field={key:string;label:string;type?:'number'|'date'|'time'|'text'|'textarea'|'boolean';options?:{value:string;label:string}[];wide?:boolean;optional?:boolean;min?:number;max?:number;step?:number;section?:string};
type Editor={kind:string;id?:string;title:string;fields:Field[];values:Values;attachment?:boolean};
const tabs=[{id:'today',title:'היום שלי',Icon:Clock3},{id:'calendar',title:'לוח חודשי',Icon:CalendarDays},{id:'summary',title:'סיכום חודש',Icon:ChartColumn},{id:'salary',title:'שכר',Icon:Wallet},{id:'leave',title:'חופשות ומחלה',Icon:BriefcaseBusiness},{id:'trips',title:'נסיעה לחו״ל',Icon:Plane},{id:'expenses',title:'הוצאות נסיעה',Icon:Receipt},{id:'report',title:'דוח שעות',Icon:FileText},{id:'documents',title:'מסמכים',Icon:FolderOpen}];
const categoryNames:Record<string,string>={HOTEL:'מלון',FLIGHT:'טיסה',TAXI:'מונית / תחבורה',MEALS:'ארוחות',PARKING:'חניה',OTHER:'אחר'};
const documentNames:Record<string,string>={CONTRACT:'חוזה עבודה',PAYSLIP:'תלוש שכר',TRAVEL:'נסיעות',TIME_OFF:'מחלה / חופשה',RECEIPT:'קבלה',OTHER:'אחר'};
const money=(value:number,currency='ILS')=>new Intl.NumberFormat('he-IL',{style:'currency',currency,maximumFractionDigits:2}).format(value);
const dateLabel=(value:string)=>new Intl.DateTimeFormat('he-IL',{timeZone:'UTC',dateStyle:'medium'}).format(new Date(`${value}T00:00:00Z`));
const options=(items:Record<string,string>)=>Object.entries(items).map(([value,label])=>({value,label}));
const numeric=(key:string,label:string,min=0,max=10000000,step=0.01):Field=>({key,label,type:'number',min,max,step});
const dateField=(key:string,label:string):Field=>({key,label,type:'date'});
const notes:Field={key:'notes',label:'הערות (לא חובה)',type:'textarea',wide:true,optional:true};
async function request(path:string,data?:object,method='POST'){const response=await fetch(`/api/work/${path}`,{method,headers:method==='GET'?undefined:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error??'לא ניתן לבצע את הפעולה.');return result;}
function Panel({title,children,actions,className=''}:{title:string;children:ReactNode;actions?:ReactNode;className?:string}){return <section className={`work-panel ${className}`}><div className="work-panel-heading"><h2>{title}</h2>{actions}</div>{children}</section>;}
function Metrics({items}:{items:{label:string;value:string}[]}){return <div className="work-metrics">{items.map(item=><article key={item.label}><small>{item.label}</small><strong>{item.value}</strong></article>)}</div>;}
function Empty({children='עדיין אין רשומות להצגה.'}:{children?:ReactNode}){return <p className="work-empty">{children}</p>;}
function WorkForm({editor,onClose,onSave}:{editor:Editor;onClose:()=>void;onSave:(values:Values,file:File|null)=>Promise<void>}){
  const ref=useRef<HTMLDialogElement>(null),[values,setValues]=useState(editor.values),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ratePreview,setRatePreview]=useState('');
  useEffect(()=>{ref.current?.showModal();},[]);
  useEffect(()=>setRatePreview(''),[values.date,values.currency,values.abroad]);
  return <dialog ref={ref} className="modal work-modal" onCancel={event=>{if(busy)event.preventDefault();else onClose();}} onClick={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><form onSubmit={async event=>{event.preventDefault();setError('');setBusy(true);try{await onSave(values,file);onClose();}catch(error){setError(error instanceof Error?error.message:'לא ניתן לשמור.');}finally{setBusy(false);}}}>
    <div className="modal-heading"><div><span className="eyebrow">עבודה</span><h2>{editor.title}</h2></div><button type="button" className="icon-button" aria-label="סגירה" disabled={busy} onClick={onClose}><X/></button></div>
    <div className="work-form-grid">{editor.fields.map(field=><div key={field.key} className={field.wide?'work-field full':'work-field'}>{field.section&&<h3 className="work-form-section">{field.section}</h3>}<label><span>{field.label}</span>{field.key==='workDays'?<span className="work-weekdays">{['א׳','ב׳','ג׳','ד׳','ה׳','ו׳','ש׳'].map((day,index)=>{const chosen=String(values.workDays)?String(values.workDays).split(',').map(Number):[];return <button key={day} type="button" aria-pressed={chosen.includes(index)} onClick={()=>setValues(v=>({...v,workDays:(chosen.includes(index)?chosen.filter(value=>value!==index):[...chosen,index]).sort().join(',')}))}>{day}</button>;})}</span>:field.type==='date'?<IsraeliDatePicker label={field.label} value={String(values[field.key]??'')||null} required={!field.optional} onChange={value=>setValues(v=>({...v,[field.key]:value}))}/>:field.type==='time'?<TimePicker label={field.label} value={String(values[field.key]??'')} required={!field.optional} onChange={value=>setValues(v=>({...v,[field.key]:value}))}/>:field.type==='boolean'?<span className="work-toggle"><span>{values[field.key]?'כן':'לא'}</span><input type="checkbox" checked={Boolean(values[field.key])} onChange={event=>setValues(v=>({...v,[field.key]:event.target.checked}))}/></span>:field.options?<select value={String(values[field.key]??'')} required={!field.optional} onChange={event=>setValues(v=>({...v,[field.key]:event.target.value}))}>{field.optional&&<option value="">ללא שיוך</option>}{field.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.type==='textarea'?<textarea rows={2} maxLength={2000} value={String(values[field.key]??'')} onChange={event=>setValues(v=>({...v,[field.key]:event.target.value}))}/>:<input type={field.type??'text'} value={String(values[field.key]??'')} min={field.min} max={field.max} step={field.step} maxLength={field.type==='text'||!field.type?2000:undefined} required={!field.optional} inputMode={field.type==='number'?'decimal':undefined} onChange={event=>{const value=event.target.value;setValues(v=>({...v,[field.key]:field.type==='number'?(value===''?null:Number(value)):value}));}}/>}</label></div>)}</div>
    {editor.kind==='expenses'&&<div className="work-rate-preview"><button type="button" className="button secondary" disabled={busy} onClick={async()=>{setError('');setBusy(true);try{const result=await request(`rate?currency=${encodeURIComponent(values.abroad?String(values.currency):'ILS')}&date=${encodeURIComponent(String(values.date))}`,undefined,'GET');setRatePreview(`שער לשקל: ${result.exchangeRate} · תאריך שער ${dateLabel(result.rateDate)} · ${result.rateSource}. שער ידני בשדה גובר על השער האוטומטי.`);}catch(error){setError(error instanceof Error?error.message:'שער לא זמין.');}finally{setBusy(false);}}}>בדיקת שער לפי תאריך ההוצאה</button>{ratePreview&&<p role="status">{ratePreview}</p>}<small>השער נשמר עם ההוצאה. בימים ללא פרסום שער, מוצג תאריך השער הזמין האחרון.</small></div>}
    {editor.attachment&&<div className="work-attachment"><label>מסמך / קבלה (PDF או תמונה, עד 3 MB)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><label className="button secondary"><Camera size={18}/>צילום קבלה<input className="work-camera-input" type="file" accept="image/*" capture="environment" onChange={event=>setFile(event.target.files?.[0]??null)}/></label>{file&&<small>{file.name}</small>}</div>}
    {error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>ביטול</button><button className="button primary" disabled={busy}>{busy?'שומר…':'שמירה'}</button></div>
  </form></dialog>;
}
function ConfirmDelete({onClose,onConfirm}:{onClose:()=>void;onConfirm:()=>Promise<void>}){const ref=useRef<HTMLDialogElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{ref.current?.showModal();},[]);return <dialog className="modal small-modal" ref={ref} onCancel={event=>{if(busy)event.preventDefault();else onClose();}} onClick={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><div className="modal-heading"><div><span className="eyebrow">עבודה</span><h2>מחיקת הרשומה</h2></div><button className="icon-button" aria-label="סגירה" disabled={busy} onClick={onClose}><X/></button></div><p>הרשומה תימחק. מחיקת נסיעה משאירה את ההוצאות והמסמכים במאגר, ללא שיוך לנסיעה.</p>{error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={onClose}>ביטול</button><button className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await onConfirm();onClose();}catch(error){setError(error instanceof Error?error.message:'לא ניתן למחוק.');}finally{setBusy(false);}}}>מחיקה</button></div></dialog>;}
export function WorkWorkspace({initial}:{initial:WorkData}){
  const [data,setData]=useState(initial),[tab,setTab]=useState('today'),[month,setMonth]=useState(initial.today.slice(0,7)),[selectedDay,setSelectedDay]=useState(initial.today),[selectedTrip,setSelectedTrip]=useState(''),[expenseFilter,setExpenseFilter]=useState('all'),[docFilter,setDocFilter]=useState('all'),[editor,setEditor]=useState<Editor|null>(null),[removing,setRemoving]=useState<{kind:string;id:string}|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState<number|null>(null);
  useEffect(()=>setData(initial),[initial]);
  const active=data.entries.find(row=>row.startedAt&&!row.endedAt),contract=data.contract;
  useEffect(()=>{setNow(Date.now());const timer=window.setInterval(()=>setNow(Date.now()),active?1000:60000);return()=>window.clearInterval(timer);},[active?.id]);
  const liveNow=now??Date.now(),summary=monthSummary(data.entries,month,contract,liveNow),today=now?dayKey(new Date(now),data.timezone):data.today;
  const timeLabel=(value:string|null)=>value?new Intl.DateTimeFormat('he-IL',{timeZone:data.timezone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value)):'—';
  async function refresh(){setData(await request('data',undefined,'GET'));}
  async function perform(action:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice('נשמר.');}catch(error){setError(error instanceof Error?error.message:'לא ניתן לשמור.');}finally{setBusy(false);}}
  async function upload(file:File,category:string,tripId?:string|null,entryId?:string|null){if(file.size>3*1024*1024)throw new Error('ניתן להעלות מסמך עד 3 MB.');const form=new FormData();form.set('file',file);form.set('category',category);if(tripId)form.set('tripId',tripId);if(entryId)form.set('entryId',entryId);const response=await fetch('/api/work/documents',{method:'POST',body:form}),result=await response.json();if(!response.ok)throw new Error(result.error??'לא ניתן להעלות מסמך.');return result.id as string;}
  const tripField:Field={key:'tripId',label:'שיוך לנסיעה (לא חובה)',options:data.trips.map(trip=>({value:trip.id,label:trip.destination})),optional:true,wide:true};
  function editEntry(row?:WorkEntryRow,type='WORK',date=today){setEditor({kind:'entries',id:row?.id,title:row?'עריכת רשומת יום':'הוספת רשומת יום',attachment:true,fields:[{key:'type',label:'סוג יום',options:options(workTypes)},dateField('date','תאריך'),{key:'startTime',label:'כניסה (לא חובה להיעדרות)',type:'time',optional:true},{key:'endTime',label:'יציאה (לא חובה להיעדרות)',type:'time',optional:true},numeric('breakMinutes','הפסקה בדקות',0,1440,1),dateField('endDate','תאריך יציאה'),{key:'overtimeApproved',label:'שעות נוספות מאושרות',type:'boolean'},numeric('distanceKm','מרחק נסיעה בק״מ',0,100000),tripField,notes],values:row?{...row,startTime:row.startedAt?timeLabel(row.startedAt):'',endTime:row.endedAt?timeLabel(row.endedAt):'',endDate:row.endedAt?dayKey(new Date(row.endedAt),data.timezone):row.date}:{type,date,startTime:['WORK','HOME'].includes(type)?'08:00':'',endTime:['WORK','HOME'].includes(type)?'16:54':'',endDate:date,breakMinutes:['WORK','HOME'].includes(type)?contract.defaultBreakMinutes:0,overtimeApproved:false,distanceKm:0,tripId:selectedTrip||null,notes:''}});}
  function addLeave(type:string){setEditor({kind:'time-off',title:type==='SICK'?'הוספת מחלה':'בקשת חופשה',attachment:true,fields:[dateField('startDate','מתאריך'),dateField('endDate','עד תאריך'),notes],values:{type,startDate:today,endDate:today,notes:''}});}
  function editTrip(row?:WorkTripRow){setEditor({kind:'trips',id:row?.id,title:row?'עריכת נסיעה לחו״ל':'נסיעה חדשה לחו״ל',fields:[{key:'destination',label:'יעד',wide:true},dateField('startDate','יציאה'),dateField('endDate','חזרה'),{key:'status',label:'סטטוס',options:options({DRAFT:'טיוטה',APPROVED:'מאושר',COMPLETED:'הסתיים'})},{key:'project',label:'שם הפרויקט',optional:true},{key:'client',label:'לקוח',optional:true},{key:'orderNumber',label:'מספרי הזמנה',optional:true},{key:'purpose',label:'מטרת הנסיעה',type:'textarea',optional:true,wide:true},{key:'flightDetails',label:'טיסות',type:'textarea',optional:true,wide:true},{key:'hotelDetails',label:'מלון',type:'textarea',optional:true,wide:true},{key:'participants',label:'משתתפים',type:'textarea',optional:true,wide:true},numeric('perDiem','אש״ל ליום'),{key:'perDiemCurrency',label:'מטבע האש״ל',options:options({ILS:'₪ ILS',USD:'$ USD',EUR:'€ EUR',GBP:'£ GBP',CHF:'CHF',CAD:'CAD',AUD:'AUD',JPY:'JPY'})}],values:row?{...row.details,destination:row.destination,startDate:row.startDate,endDate:row.endDate,status:row.status}:{destination:'',startDate:today,endDate:today,status:'DRAFT',project:'',client:'',purpose:'',orderNumber:'',flightDetails:'',hotelDetails:'',participants:'',perDiem:0,perDiemCurrency:'ILS'}});}
  function editExpense(row?:WorkExpenseRow){setEditor({kind:'expenses',id:row?.id,title:row?'עריכת הוצאה':'הוספת הוצאה',attachment:true,fields:[{key:'abroad',label:'הוצאה בחו״ל',type:'boolean'},{key:'category',label:'קטגוריה',options:options(categoryNames)},numeric('amount','סכום',0.01),{key:'currency',label:'מטבע',options:options({ILS:'₪ ILS',USD:'$ USD',EUR:'€ EUR',GBP:'£ GBP',CHF:'CHF',CAD:'CAD',AUD:'AUD',JPY:'JPY'})},dateField('date','תאריך ההוצאה'),{key:'paymentSource',label:'מקור תשלום',options:options({PERSONAL:'אני',COMPANY:'כרטיס חברה'})},{...numeric('exchangeRate','שער ידני לשקל (לא חובה)',0.000001,1000000,0.000001),optional:true,wide:true},{key:'reimbursable',label:'נדרש החזר אישי',type:'boolean'},{key:'paid',label:'ההחזר שולם',type:'boolean'},tripField,notes],values:row?{...row,abroad:row.currency!=='ILS',exchangeRate:row.rateSource==='ידני'?row.exchangeRate:null}:{abroad:Boolean(selectedTrip),category:'OTHER',amount:null,currency:selectedTrip?'EUR':'ILS',date:today,paymentSource:'PERSONAL',exchangeRate:null,reimbursable:false,paid:false,tripId:selectedTrip||null,documentId:null,notes:''}});}
  function editContract(){const labels:Record<string,string>={baseSalary:'שכר בסיס ברוטו (₪)',standardMinutes:'יום עבודה רגיל בדקות (504 = 8:24)',defaultBreakMinutes:'הפסקה מתוכננת בדקות',monthlyHours:'שעות חודשיות לחישוב תעריף',contributionBasePercent:'בסיס להפרשות (% משכר הבסיס)',mealPerDay:'סיבוס ליום עבודה (₪)',travelAllowance:'נסיעות חודשי (₪)',vacationDays:'זכאות חופשה שנתית (ימים)',vacationCarryover:'יתרת חופשה משנים קודמות',sickEntitlement:'יתרת זכאות מחלה שנתית (0 = לא הוגדרה)',sickPayPercent:'תשלום מחלה מהיום הראשון (%)',employeePensionPercent:'פנסיה עובד (%)',employerPensionPercent:'פנסיה מעסיק (%)',severancePercent:'פיצויים מעסיק (%)',employeeTrainingPercent:'השתלמות עובד (%)',employerTrainingPercent:'השתלמות מעסיק (%)',overtimeFirstMinutes:'משך מדרגה ראשונה בדקות',overtimeFirstPercent:'שעות נוספות מדרגה ראשונה (%)',overtimeNextPercent:'שעות נוספות יתר הזמן (%)'};setEditor({kind:'settings',title:'תנאי החוזה',fields:[...Object.entries(labels).map(([key,label])=>({...numeric(key,label, key==='standardMinutes'||key==='monthlyHours'?1:0,key.endsWith('Minutes')?1440:key.endsWith('Percent')?300:10000000,key.endsWith('Minutes')?1:0.01),wide:key==='overtimeNextPercent'})),{key:'workDays',label:'ימי עבודה',options:options({'0,1,2,3,4':'ראשון עד חמישי','1,2,3,4,5':'שני עד שישי','0,1,2,3,4,5':'ראשון עד שישי','0,1,2,3,4,5,6':'כל השבוע'}),wide:true}],values:{...contract,workDays:contract.workDays.join(',')}});}
  function addDocument(){setEditor({kind:'documents',title:'העלאת מסמך',fields:[{key:'category',label:'סוג מסמך',options:options(documentNames),wide:true},tripField],values:{category:'OTHER',tripId:selectedTrip||null},attachment:true});}
  async function saveEditor(values:Values,file:File|null){if(!editor)return;setNotice('');
    if(editor.kind==='documents'){if(!file)throw new Error('יש לבחור מסמך.');await upload(file,String(values.category),String(values.tripId||'')||null);}
    else{
      let payload:object=values;
      if(editor.kind==='entries'){const row=values;payload={date:row.date,type:row.type,startTime:row.startTime||null,endTime:row.endTime||null,endDate:row.endDate||row.date,breakMinutes:Number(row.breakMinutes),overtimeApproved:Boolean(row.overtimeApproved),distanceKm:Number(row.distanceKm),tripId:row.tripId||null,notes:row.notes};}
      if(editor.kind==='settings')payload={...values,workDays:String(values.workDays)?String(values.workDays).split(',').map(Number):[]};
      if(editor.kind==='expenses'){const fields=values;payload={tripId:fields.tripId||null,date:fields.date,category:fields.category,amount:fields.amount,currency:fields.abroad?fields.currency:'ILS',exchangeRate:fields.exchangeRate||null,paymentSource:fields.paymentSource,reimbursable:fields.paymentSource==='COMPANY'?false:fields.reimbursable,paid:fields.paid,notes:fields.notes,documentId:fields.documentId||null};if(file){payload={...payload,documentId:await upload(file,'RECEIPT',String(values.tripId||'')||null)};}}
      const result=await request(`${editor.kind}${editor.id?`/${editor.id}`:''}`,payload,editor.id?'PATCH':'POST');
      if(file&&editor.kind!=='expenses'){try{await upload(file,['SICK','VACATION'].includes(String(values.type))?'TIME_OFF':'OTHER',String(values.tripId||'')||null,result.id);}catch(error){setNotice(`הרשומה נשמרה; העלאת המסמך נכשלה: ${error instanceof Error?error.message:''}. ניתן להוסיף אותו במסמכים.`);}}
    }
    await refresh();setNotice(value=>value||'נשמר.');
  }
  function entryList(entries:WorkEntryRow[]){return entries.length?<div className="work-list">{entries.map(entry=><article key={entry.id}><div><strong>{workTypes[entry.type]} · {dateLabel(entry.date)}</strong><p>{entry.startedAt?`${timeLabel(entry.startedAt)} — ${timeLabel(entry.endedAt)} · ${workClock(shiftMinutes(entry,liveNow))} שעות · הפסקה ${workClock(entry.breakMinutes)}`:'יום ללא שעות עבודה'}{entry.distanceKm?` · ${entry.distanceKm} ק״מ`:''}</p>{entry.overtimeApproved&&<small className="work-badge">שעות נוספות מאושרות</small>}{entry.notes&&<p>{entry.notes}</p>}{data.documents.filter(doc=>doc.entryId===entry.id).map(doc=><a key={doc.id} href={`/api/work/documents/${doc.id}`} target="_blank" rel="noreferrer">{doc.name}</a>)}</div><div className="work-row-actions"><button className="icon-button" aria-label="עריכת רשומה" onClick={()=>editEntry(entry)}><Pencil size={17}/></button><button className="icon-button" aria-label="מחיקת רשומה" onClick={()=>setRemoving({kind:'entries',id:entry.id})}><Trash2 size={17}/></button></div></article>)}</div>:<Empty/>;}
  const days=monthDays(month),firstWeekday=new Date(`${month}-01T00:00:00Z`).getUTCDay(),viewDay=selectedDay.startsWith(month)?selectedDay:days[0],trip=data.trips.find(trip=>trip.id===selectedTrip)??data.trips[0];
  const year=month.slice(0,4),yearLeave=data.entries.filter(row=>row.date.startsWith(year));
  const usedVacation=new Set(yearLeave.filter(row=>row.type==='VACATION').map(row=>row.date)).size,usedSick=new Set(yearLeave.filter(row=>row.type==='SICK').map(row=>row.date)).size;
  const expenses=data.expenses.filter(row=>selectedTrip?row.tripId===selectedTrip:row.date.startsWith(month));
  const docs=data.documents.filter(doc=>(docFilter==='all'||doc.category===docFilter)&&(!selectedTrip||doc.tripId===selectedTrip));
  const canWarnDay=(date:string)=>date<=today&&contract.workDays.includes(new Date(`${date}T00:00:00Z`).getUTCDay());
  const deficit=summary.days.reduce((sum,day)=>sum+(canWarnDay(day.date)&&!day.sick&&!day.vacation?Math.max(0,contract.standardMinutes-day.minutes):0),0);
  return <div className="work-hub"><header className="work-heading"><div><span className="eyebrow">SBO · עבודה</span><h1>מרכז העבודה שלי</h1><p>שעות, שכר, נסיעות ומסמכים במקום אחד</p></div><button className="button secondary" onClick={editContract}><Settings size={18}/>תנאי חוזה</button></header>
    <nav className="work-tabs" aria-label="מסכי עבודה">{tabs.map(({id,title,Icon})=><button key={id} type="button" aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>{setTab(id);setError('');}}><Icon size={18}/>{title}</button>)}</nav>
    <div className="work-toolbar"><div className="work-month"><button className="icon-button" aria-label="חודש קודם" onClick={()=>{const date=new Date(`${month}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()-1);setMonth(date.toISOString().slice(0,7));}}><ChevronRight size={18}/></button><label>חודש<input type="month" value={month} aria-label="חודש עבודה" onChange={event=>{if(event.target.value)setMonth(event.target.value);}}/></label><button className="icon-button" aria-label="חודש הבא" onClick={()=>{const date=new Date(`${month}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()+1);setMonth(date.toISOString().slice(0,7));}}><ChevronLeft size={18}/></button></div>{['trips','expenses','documents'].includes(tab)&&<label className="work-trip-filter">נסיעה<select value={selectedTrip} onChange={event=>setSelectedTrip(event.target.value)}><option value="">כל הנסיעות</option>{data.trips.map(trip=><option key={trip.id} value={trip.id}>{trip.destination}</option>)}</select></label>}</div>
    {error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p className="feedback" role="status">{notice}</p>}
    {tab==='today'&&<><Panel title={active?(active.pausedAt?'כרגע בהפסקה':'כרגע בעבודה'):'מוכנים ליום העבודה'} className="work-live"><div className="work-live-main"><div className="work-timer" role="img" aria-label={`עבודה ${workClock(active?shiftMinutes(active,liveNow):0)} מתוך ${workClock(contract.standardMinutes)}`} style={{background:`conic-gradient(#ebc568 ${Math.min(100,(active?shiftMinutes(active,liveNow):0)/contract.standardMinutes*100)}%, #173e53 0)`}}><div><strong>{workClock(active?shiftMinutes(active,liveNow):0)}</strong><small>מתוך {workClock(contract.standardMinutes)}</small></div></div><div className="work-live-details"><span>כניסה <b>{active?timeLabel(active.startedAt):'—'}</b></span><span>הפסקה <b>{workClock((active?.breakMinutes??0)+(active?.pausedAt?Math.floor((liveNow-Date.parse(active.pausedAt))/60000):0))}</b></span><span>יום רגיל: {workClock(contract.standardMinutes)} + הפסקה מתוכננת {workClock(contract.defaultBreakMinutes)}</span><button className="button primary" disabled={busy} onClick={()=>perform(()=>request('clock',{action:active?'stop':'start'}))}>{active?'סיום עבודה':'התחל עבודה'}</button></div></div><div className="work-quick-actions"><button disabled={busy||!active} onClick={()=>perform(()=>request('clock',{action:active?.pausedAt?'resume':'pause'}))}><Coffee/>{active?.pausedAt?'חזרה מהפסקה':'הפסקה'}</button><button onClick={()=>editEntry(undefined,'TRAVEL')}><MapPin/>נסיעה</button><button disabled={busy} onClick={()=>perform(()=>request('clock',{action:active?'type':'start',type:'HOME'}))}><Home/>עבודה מהבית</button><button onClick={()=>editEntry(undefined,'OTHER')}><Plus/>אחר</button></div></Panel><Metrics items={[{label:'שעות בפועל',value:workClock(summary.minutes)},{label:'שעות נוספות מאושרות',value:workClock(summary.approvedMinutes)},{label:'ימי מחלה',value:String(summary.sickDays)},{label:'ימי חופשה',value:String(summary.vacationDays)}]}/><Panel title="רשומות היום" actions={<button className="button secondary" onClick={()=>editEntry()}><Plus size={18}/>הוספת יום</button>}>{entryList(data.entries.filter(entry=>entry.date===today))}</Panel></>}
    {tab==='calendar'&&<div className="work-columns"><Panel title="לוח חודשי"><div className="work-calendar">{['א','ב','ג','ד','ה','ו','ש'].map(day=><b key={day}>{day}</b>)}{Array.from({length:firstWeekday},(_,i)=><span key={`blank${i}`}/>)}{days.map(date=>{const statuses=[...new Set(data.entries.filter(entry=>entry.date===date).map(entry=>entry.type))],travel=data.trips.some(trip=>trip.startDate<=date&&trip.endDate>=date);if(travel&&!statuses.includes('TRAVEL'))statuses.push('TRAVEL');return <button key={date} className={`${date===viewDay?'selected':''} ${date===today?'today':''}`} onClick={()=>setSelectedDay(date)}><strong>{Number(date.slice(8))}</strong>{statuses.slice(0,2).map(type=><span key={type} className={`work-day-badge ${type.toLowerCase()}`}>{workTypes[type]}</span>)}</button>;})}</div></Panel><Panel title={dateLabel(viewDay)} actions={<button className="icon-button" aria-label="הוספת רשומה לתאריך" onClick={()=>editEntry(undefined,'WORK',viewDay)}><Plus/></button>}>{entryList(data.entries.filter(entry=>entry.date===viewDay))}{data.trips.filter(trip=>trip.startDate<=viewDay&&trip.endDate>=viewDay).map(trip=><p key={trip.id}><Plane size={16}/> {trip.destination} · נסיעה מתוכננת (שעות מוזנות בנפרד)</p>)}</Panel></div>}
    {tab==='summary'&&<><Metrics items={[{label:'ימי עבודה בפועל',value:String(summary.workedDays)},{label:'שעות שנרשמו',value:workClock(summary.minutes)},{label:'נוספות מאושרות',value:workClock(summary.approvedMinutes)}]}/><div className="work-columns"><Panel title="התפלגות ימים"><DayDistribution summary={summary}/></Panel><Panel title="שעות לפי שבוע"><div className="work-week-bars">{Array.from({length:Math.ceil((days.length+firstWeekday)/7)},(_,index)=>{const subset=summary.days.filter(day=>Math.floor((Number(day.date.slice(8))-1+firstWeekday)/7)===index),regular=subset.reduce((sum,d)=>sum+d.regular,0),overtime=subset.reduce((sum,d)=>sum+d.approvedFirst+d.approvedNext,0);return <div key={index}><span>שבוע {index+1}</span><div role="img" aria-label={`שבוע ${index+1}: רגילות ${workClock(regular)}, נוספות ${workClock(overtime)}`}><i style={{width:`${Math.min(100,regular/(contract.standardMinutes*7)*100)}%`}}/><b style={{width:`${Math.min(100,overtime/(contract.standardMinutes*7)*100)}%`}}/></div><small>{workClock(regular)} רגילות · {workClock(overtime)} נוספות</small></div>;})}</div></Panel></div><Panel title="בדיקת השלמת שעות"><p>{deficit?`חוסר רשום עד היום: ${workClock(deficit)} שעות.`:'אין חוסר בשעות שנבדקו.'} ימי מחלה וחופשה אינם נחשבים חוסר. ימים ללא רישום עשויים להופיע כחוסר עד להשלמת הדוח.</p></Panel></>}
    {tab==='salary'&&<><Panel title="אומדן שכר ברוטו"><strong className="work-salary-total">{money(summary.gross)}</strong><p>לפי החוזה שנשמר · בסיס חודשי מלא · אומדן לפני מס וניכויים. סיבוס מוצג בנפרד מהברוטו.</p><div className="work-breakdown">{[['שכר בסיס',contract.baseSalary],['שעות נוספות מאושרות',summary.overtimePay],['נסיעות',contract.travelAllowance],['התאמת תשלום מחלה לפי החוזה',summary.sickAdjustment]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{money(Number(value))}</b></div>)}<div><span>סיבוס · {money(contract.mealPerDay)} × {summary.workedDays} ימי עבודה</span><b>{money(summary.meals)}</b></div></div></Panel><div className="work-columns"><Panel title="הפרשות עובד"><p>בסיס להפרשות: {money(summary.socialBase)} ({contract.contributionBasePercent}% מהבסיס)</p><div className="work-breakdown"><div><span>פנסיה · {contract.employeePensionPercent}%</span><b>{money(summary.socialBase*contract.employeePensionPercent/100)}</b></div><div><span>קרן השתלמות · {contract.employeeTrainingPercent}%</span><b>{money(summary.socialBase*contract.employeeTrainingPercent/100)}</b></div></div></Panel><Panel title="הפרשות מעסיק"><div className="work-breakdown">{[['פנסיה',contract.employerPensionPercent],['השתלמות',contract.employerTrainingPercent],['פיצויים',contract.severancePercent]].map(([name,percent])=><div key={String(name)}><span>{name} · {percent}%</span><b>{money(summary.socialBase*Number(percent)/100)}</b></div>)}</div></Panel></div><p className="module-hint">תעריף בסיס: {money(contract.baseSalary/contract.monthlyHours)}/שעה. מדרגה ראשונה {contract.overtimeFirstMinutes} דקות ב־{contract.overtimeFirstPercent}%, והיתרה ב־{contract.overtimeNextPercent}%. אלו פרמטרים אישיים ניתנים לעריכה.</p></>}
    {tab==='leave'&&<><Metrics items={[{label:`זכאות חופשה ${year} + יתרה`,value:String(contract.vacationDays+contract.vacationCarryover)},{label:'ימי חופשה שנוצלו',value:String(usedVacation)},{label:'חופשה שנותרה',value:String(contract.vacationDays+contract.vacationCarryover-usedVacation)},{label:'מחלה שנוצלה',value:String(usedSick)}]}/><Panel title="חופשות ומחלה" actions={<div className="work-actions"><button className="button primary" onClick={()=>addLeave('VACATION')}><Plus size={18}/>בקשת חופשה</button><button className="button secondary" onClick={()=>addLeave('SICK')}><Plus size={18}/>הוספת מחלה</button></div>}><p>מחלה: {contract.sickPayPercent}% תשלום מהיום הראשון לפי החוזה. {contract.sickEntitlement?`זכאות שנתית ${contract.sickEntitlement}, נותרו ${contract.sickEntitlement-usedSick} ימים.`:'יתרת זכאות מחלה לא הוגדרה; ניתן להזין בתנאי החוזה.'} רישום אישי, ללא שליחה או אישור ממעסיק.</p>{entryList(yearLeave.filter(entry=>['SICK','VACATION'].includes(entry.type)))}</Panel></>}
    {tab==='trips'&&<><Panel title="נסיעות לחו״ל" actions={<button className="button primary" onClick={()=>editTrip()}><Plus size={18}/>נסיעה חדשה</button>}>{data.trips.length?<div className="work-trip-list">{data.trips.map(item=><button key={item.id} className={trip?.id===item.id?'selected':''} onClick={()=>setSelectedTrip(item.id)}><Plane size={18}/><strong>{item.destination}</strong><small>{dateLabel(item.startDate)} — {dateLabel(item.endDate)}</small></button>)}</div>:<Empty/>}</Panel>{trip&&<Panel title={trip.destination} actions={<div className="work-row-actions"><span className="work-badge">{{DRAFT:'טיוטה',APPROVED:'מאושר',COMPLETED:'הסתיים'}[trip.status]}</span><button className="icon-button" aria-label="עריכת נסיעה" onClick={()=>editTrip(trip)}><Pencil/></button><button className="icon-button" aria-label="מחיקת נסיעה" onClick={()=>setRemoving({kind:'trips',id:trip.id})}><Trash2/></button></div>}><p>{dateLabel(trip.startDate)} — {dateLabel(trip.endDate)}</p><div className="work-quick-actions">{[{label:'טיסות',Icon:Plane,action:()=>editTrip(trip)},{label:'מלון',Icon:Home,action:()=>editTrip(trip)},{label:'הוצאות',Icon:Receipt,action:()=>{setSelectedTrip(trip.id);setMonth(trip.startDate.slice(0,7));setTab('expenses');}},{label:'משתתפים',Icon:BriefcaseBusiness,action:()=>editTrip(trip)}].map(({label,Icon,action})=><button key={label} onClick={action}><Icon/>{label}</button>)}</div><div className="work-breakdown">{[['פרויקט','project'],['לקוח','client'],['מטרה','purpose'],['מספרי הזמנה','orderNumber'],['טיסות','flightDetails'],['מלון','hotelDetails'],['משתתפים','participants']].map(([label,key])=><div key={key}><span>{label}</span><b>{String(trip.details[key]||'לא הוזן')}</b></div>)}<div><span>אש״ל מתוכנן לכל ימי הנסיעה</span><b>{money(Number(trip.details.perDiem||0)*(Math.round((Date.parse(trip.endDate)-Date.parse(trip.startDate))/86400000)+1),String(trip.details.perDiemCurrency||'ILS'))}</b></div></div><h3>רשומות משויכות</h3>{entryList(data.entries.filter(entry=>entry.tripId===trip.id))}<h3>מסמכי הנסיעה</h3>{data.documents.filter(doc=>doc.tripId===trip.id).map(doc=><p key={doc.id}><a href={`/api/work/documents/${doc.id}`} target="_blank" rel="noreferrer">{doc.name}</a></p>)}<button className="button secondary" onClick={()=>{setSelectedTrip(trip.id);addDocumentForTrip(trip.id);}}>הוספת מסמך לנסיעה</button></Panel>}</>}
    {tab==='expenses'&&<><Metrics items={[{label:'הוצאות בשקלים',value:money(expenses.reduce((sum,row)=>sum+row.amount*row.exchangeRate,0))},{label:'להחזר אישי',value:money(expenses.filter(row=>row.reimbursable&&!row.paid).reduce((sum,row)=>sum+row.amount*row.exchangeRate,0))}]}/><Panel title="הוצאות נסיעה" actions={<button className="button primary" onClick={()=>editExpense()}><Plus size={18}/>הוספת הוצאה</button>}><div className="work-filter-tabs">{[['all','הכל'],['refund','להחזיר'],['paid','שולם']].map(([id,label])=><button key={id} className={expenseFilter===id?'active':''} onClick={()=>setExpenseFilter(id)}>{label}</button>)}</div><div className="work-currency-totals">{[...new Set(expenses.map(row=>row.currency))].map(currency=><span key={currency}>{money(expenses.filter(row=>row.currency===currency).reduce((sum,row)=>sum+row.amount,0),currency)} = {money(expenses.filter(row=>row.currency===currency).reduce((sum,row)=>sum+row.amount*row.exchangeRate,0))}</span>)}</div>{expenses.filter(row=>expenseFilter==='all'||(expenseFilter==='refund'?row.reimbursable&&!row.paid:row.paid)).length?<div className="work-list">{expenses.filter(row=>expenseFilter==='all'||(expenseFilter==='refund'?row.reimbursable&&!row.paid:row.paid)).map(row=><article key={row.id}><div><strong>{categoryNames[row.category]} · {money(row.amount,row.currency)}</strong><p>{dateLabel(row.date)} · {money(row.amount*row.exchangeRate)} · {row.paymentSource==='COMPANY'?'כרטיס חברה':row.reimbursable?row.paid?'הוחזר':'נדרש החזר':'תשלום אישי'}</p><small>שער {row.exchangeRate} · {dateLabel(row.rateDate)} · {row.rateSource}</small>{row.notes&&<p>{row.notes}</p>}{row.documentId&&<p><a href={`/api/work/documents/${row.documentId}`} target="_blank" rel="noreferrer">צפייה בקבלה</a></p>}</div><div className="work-row-actions"><button className="icon-button" aria-label="עריכת הוצאה" onClick={()=>editExpense(row)}><Pencil size={17}/></button><button className="icon-button" aria-label="מחיקת הוצאה" onClick={()=>setRemoving({kind:'expenses',id:row.id})}><Trash2 size={17}/></button></div></article>)}</div>:<Empty/>}</Panel></>}
    {tab==='report'&&<Panel title="דוח שעות חודשי" actions={<div className="work-actions"><a className="button secondary" href={`/api/work/export?month=${month}`}><Download size={18}/>Excel</a><a className="button primary" href={`/work/report?month=${month}`} target="_blank" rel="noreferrer"><FileText size={18}/>PDF</a></div>}><p className="module-hint">PDF נפתח בתצוגה להדפסה ושמירה. שעות נוספות בדוח כוללות אישור אישי בלבד.</p><div className="work-table-wrap"><table><thead><tr>{['תאריך','כניסה','הפסקה','יציאה','סה״כ','סוג','רגילות','נוספות מאושרות'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{reportRows(data,month).map((row,index)=><tr key={index}>{row.map((value,i)=><td key={i}>{value}</td>)}</tr>)}</tbody><tfoot><tr><td colSpan={4}>סה״כ</td><td>{workClock(summary.minutes)}</td><td/><td>{workClock(summary.days.reduce((sum,day)=>sum+day.regular,0))}</td><td>{workClock(summary.approvedMinutes)}</td></tr></tfoot></table></div></Panel>}
    {tab==='documents'&&<Panel title="המסמכים שלי" actions={<button className="button primary" onClick={addDocument}><Plus size={18}/>העלאת מסמך</button>}><div className="work-filter-tabs">{[['all','הכל'],...Object.entries(documentNames)].map(([id,label])=><button key={id} className={docFilter===id?'active':''} onClick={()=>setDocFilter(id)}>{label}</button>)}</div>{docs.length?<div className="work-list">{docs.map(doc=><article key={doc.id}><div><strong>{doc.name}</strong><p>{documentNames[doc.category]} · {Math.ceil(doc.size/1024)} KB</p></div><div className="work-row-actions"><a className="icon-button" aria-label={`צפייה ${doc.name}`} href={`/api/work/documents/${doc.id}`} target="_blank" rel="noreferrer"><FileText size={18}/></a><a className="icon-button" aria-label={`הורדת ${doc.name}`} href={`/api/work/documents/${doc.id}?download=1`}><Download size={18}/></a><button className="icon-button" aria-label="מחיקת מסמך" onClick={()=>setRemoving({kind:'documents',id:doc.id})}><Trash2 size={18}/></button></div></article>)}</div>:<Empty/>}<p className="module-hint">PDF ותמונות עד 3 MB למסמך. המסמכים נשמרים בחשבון שלך במסד הקיים.</p></Panel>}
    {editor&&<WorkForm key={`${editor.kind}-${editor.id??'new'}`} editor={editor} onClose={()=>setEditor(null)} onSave={saveEditor}/>}{removing&&<ConfirmDelete onClose={()=>setRemoving(null)} onConfirm={async()=>{await request(`${removing.kind}/${removing.id}`,undefined,'DELETE');await refresh();setNotice('נמחק.');}}/>}
  </div>;
  function addDocumentForTrip(tripId:string){setEditor({kind:'documents',title:'מסמך לנסיעה',fields:[{key:'category',label:'סוג מסמך',options:options(documentNames),wide:true},tripField],values:{category:'TRAVEL',tripId},attachment:true});}
}
function DayDistribution({summary}:{summary:ReturnType<typeof monthSummary>}){const parts=[{label:'עבודה',count:summary.days.filter(day=>day.worked&&!day.travel&&!day.sick&&!day.vacation).length,color:'#ebc568'},{label:'חופשה',count:summary.vacationDays,color:'#5cb6ca'},{label:'מחלה',count:summary.sickDays,color:'#bda6ef'},{label:'נסיעה',count:summary.days.filter(day=>day.travel&&!day.sick&&!day.vacation).length,color:'#4d91eb'}],total=parts.reduce((sum,part)=>sum+part.count,0);let position=0;const gradient=parts.map(part=>{const start=position;position+=total?part.count/total*100:0;return `${part.color} ${start}% ${position}%`;}).join(',');return <div className="work-distribution"><div className="work-donut" style={{background:total?`conic-gradient(${gradient})`:'#173e53'}} role="img" aria-label={parts.map(part=>`${part.label}: ${part.count} ימים`).join(', ')}><span><b>{total}</b>ימים רשומים</span></div><div>{parts.map(part=><p key={part.label}><i style={{background:part.color}}/>{part.label}<strong>{part.count}</strong></p>)}</div></div>;}
