ALTER TABLE "UserSettings"
ADD COLUMN IF NOT EXISTS "waterReminderEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "waterReminderStart" VARCHAR(5) NOT NULL DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS "waterReminderEnd" VARCHAR(5) NOT NULL DEFAULT '16:00',
ADD COLUMN IF NOT EXISTS "waterReminderIntervalMinutes" INTEGER NOT NULL DEFAULT 60;
