ALTER TABLE "UserSettings" ADD COLUMN IF NOT EXISTS "weeklyWorkouts" INTEGER;
ALTER TABLE "UserSettings" ADD COLUMN IF NOT EXISTS "creatineReminderEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserSettings" ADD COLUMN IF NOT EXISTS "creatineReminderTime" VARCHAR(5) NOT NULL DEFAULT '09:00';

ALTER TABLE "UserFood" ADD COLUMN IF NOT EXISTS "servingName" VARCHAR(40) NOT NULL DEFAULT 'מנה';
ALTER TABLE "UserFood" ADD COLUMN IF NOT EXISTS "servingGrams" DECIMAL(8,2) NOT NULL DEFAULT 100;

ALTER TABLE "FoodPreference" ADD COLUMN IF NOT EXISTS "lastQuantity" DECIMAL(10,2);
ALTER TABLE "FoodPreference" ADD COLUMN IF NOT EXISTS "lastUnit" VARCHAR(20);
ALTER TABLE "FoodPreference" ADD COLUMN IF NOT EXISTS "lastServingGrams" DECIMAL(8,2);
ALTER TABLE "FoodPreference" ADD COLUMN IF NOT EXISTS "lastServingName" VARCHAR(40);
