ALTER TABLE "VehicleExpense" ADD COLUMN IF NOT EXISTS "nextServiceDate" DATE;
ALTER TABLE "VehicleExpense" ADD COLUMN IF NOT EXISTS "reminderDays" INTEGER;
ALTER TABLE "VehicleExpense" ADD COLUMN IF NOT EXISTS "reminderTime" VARCHAR(5) NOT NULL DEFAULT '09:00';
