import { NextResponse } from "next/server";
import webpush from "web-push";
import { db } from "@/lib/db";

export const dynamic="force-dynamic";
const DAY=86400000;
function localParts(date:Date,timeZone:string){return Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));}
function localInstant(date:string,time:string,timeZone:string){const [y,m,d]=date.split("-").map(Number),[h,minute]=time.split(":").map(Number),wanted=Date.UTC(y,m-1,d,h,minute);let value=wanted;for(let i=0;i<3;i++){const p=localParts(new Date(value),timeZone),shown=Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute));value+=wanted-shown;}return value;}
function shift(value:string,days:number){const d=new Date(`${value}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function occurs(item:{start:string;end?:string|null;recurrence:string;days:number[];until?:string|null},date:string){const end=item.end??item.start,duration=Math.max(0,Math.round((new Date(`${end}T00:00:00Z`).getTime()-new Date(`${item.start}T00:00:00Z`).getTime())/DAY));for(let offset=0;offset<=duration;offset++){const anchor=shift(date,-offset);if(anchor<item.start||(item.until&&anchor>item.until))continue;const current=new Date(`${anchor}T00:00:00Z`),base=new Date(`${item.start}T00:00:00Z`);if(item.recurrence==="NONE"&&anchor===item.start)return true;if(item.recurrence==="DAILY")return true;if(item.recurrence==="WEEKLY"&&current.getUTCDay()===base.getUTCDay())return true;if(item.recurrence==="MONTHLY"&&current.getUTCDate()===base.getUTCDate())return true;if(item.recurrence==="YEARLY"&&current.getUTCMonth()===base.getUTCMonth()&&current.getUTCDate()===base.getUTCDate())return true;if(item.recurrence==="CUSTOM"&&item.days.includes(current.getUTCDay()))return true;}return false;}

export async function POST(request:Request){
  if(!process.env.DISPATCH_SECRET||request.headers.get("authorization")!==`Bearer ${process.env.DISPATCH_SECRET}`)return NextResponse.json({error:"Unauthorized"},{status:401});
  const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,privateKey=process.env.VAPID_PRIVATE_KEY;
  if(!publicKey||!privateKey)return NextResponse.json({error:"Push keys are not configured"},{status:503});
  const current=new Date(),monthStart=new Date(Date.UTC(current.getUTCFullYear(),current.getUTCMonth(),1));
  await db.task.deleteMany({where:{deletedAt:{lt:monthStart}}});
  webpush.setVapidDetails("mailto:sbo.notifications@gmail.com",publicKey,privateKey);
  const now=Date.now(),users=await db.user.findMany({where:{pushSubscriptions:{some:{enabled:true}}},include:{settings:true,pushSubscriptions:{where:{enabled:true}},tasks:{where:{deletedAt:null,reminderMinutes:{not:null},startTime:{not:null},status:{notIn:["DONE","CANCELLED"]}}},calendarEvents:{where:{reminderMinutes:{not:null},time:{not:null}}}}});
  let sent=0;
  for(const user of users){const zone=user.settings?.timezone??"Asia/Jerusalem",parts=localParts(new Date(now),zone),today=`${parts.year}-${parts.month}-${parts.day}`;const items=[...user.tasks.filter(t=>t.startDate&&t.startTime&&t.reminderMinutes!==null).map(t=>({kind:"task",id:t.id,title:t.title,start:t.startDate!.toISOString().slice(0,10),end:t.endDate?.toISOString().slice(0,10),time:t.startTime!,reminder:t.reminderMinutes!,recurrence:t.recurrence,days:t.recurrenceDays,until:t.recurrenceUntil?.toISOString().slice(0,10)})),...user.calendarEvents.filter(e=>e.time&&e.reminderMinutes!==null).map(e=>({kind:"event",id:e.id,title:e.title,start:e.date.toISOString().slice(0,10),end:e.endDate?.toISOString().slice(0,10),time:e.time!,reminder:e.reminderMinutes!,recurrence:e.recurrence,days:e.recurrenceDays,until:e.recurrenceUntil?.toISOString().slice(0,10)}))];for(const item of items){for(let ahead=0;ahead<=7;ahead++){const date=shift(today,ahead);if(!occurs(item,date))continue;const notifyAt=localInstant(date,item.time,zone)-item.reminder*60000;if(now<notifyAt||now-notifyAt>=120000)continue;const occurrenceKey=`${item.kind}:${item.id}:${date}:${item.time}:${item.reminder}`;for(const sub of user.pushSubscriptions){try{await db.pushDelivery.create({data:{subscriptionId:sub.id,occurrenceKey}});}catch{continue;}try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},JSON.stringify({title:`SBO · ${item.title}`,body:item.reminder?`בעוד ${item.reminder} דקות`:`הגיע הזמן`,url:"/tasks"}));sent++;}catch(error){await db.pushDelivery.deleteMany({where:{subscriptionId:sub.id,occurrenceKey}});const status=(error as {statusCode?:number}).statusCode;if(status===404||status===410)await db.pushSubscription.update({where:{id:sub.id},data:{enabled:false}});}}}}}
  return NextResponse.json({ok:true,sent});
}
